=== tudelft/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (doc,settings_file*,settings*,dep?,header?,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT doc (description,(define|configure|section)*)>
<!ELEMENT settings_file (file*)>
<!ELEMENT settings (dl_settings?)>
<!ELEMENT dep (depends?,conflicts?,provides?,recommends?,suggests?)>
<!ELEMENT depends (#PCDATA)>
<!ELEMENT conflicts (#PCDATA)>
<!ELEMENT provides (#PCDATA)>
<!ELEMENT recommends (#PCDATA)>
<!ELEMENT suggests (#PCDATA)>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|include|flag|file|file_arch|raw|test)*>
<!ELEMENT test (configure|define|include|file|file_arch|shell)*>
<!ELEMENT section (define|configure)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT shell EMPTY>
<!ELEMENT raw (#PCDATA)>
<!ELEMENT dl_settings (dl_setting|dl_settings)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED
task CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST event
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED
class CDATA #IMPLIED
min_len CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST makefile
target CDATA #IMPLIED
firmware CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST section
name CDATA #REQUIRED
prefix CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #IMPLIED
case CDATA #IMPLIED
default CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
integer CDATA #IMPLIED
unit CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST include
name CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST shell
cmd CDATA #REQUIRED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST settings_file
name CDATA #REQUIRED
>

<!ATTLIST settings
name CDATA #IMPLIED
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
header CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ATTLIST test
arch CDATA #IMPLIED
firmware CDATA #IMPLIED
>

=== tudelft/paparazzi/conf/modules/eff_scheduling_rotwing_V2.xml
<!DOCTYPE module SYSTEM "module.dtd">
<module name="eff_scheduling_rotwing_V2" dir="ctrl">
  <doc>
    <description>T
      The control effectiveness scheduler for the rotating wing quadplane drone type
     - it requires a servo called ROTATION_MECH
    </description>
    <section name="ROTWING" prefix="ROTWING_EFF_SCHED_">
      <define name="IXX_BODY" value="0"  description=""/>
      <define name="IYY_BODY" value="0"  description=""/>
      <define name="IZZ" value="0"       description=""/>
      <define name="IXX_WING" value="0"  description=""/>
      <define name="IYY_WING" value="0"  description=""/>
      <define name="M" value="0"         description=""/>
      <define name="ROLL_ARM" value="0"  description=""/>
      <define name="PITCH_ARM" value="0" description=""/>
      <define name="HOVER_DF_DPPRZ" value="0" description=""/>
      <define name="HOVER_ROLL_PITCH_COEF" value="{0,0}" description=""/>
    </section>
  </doc>
    <settings>
   <dl_settings>
     <dl_settings NAME="eff_sched">
       <dl_setting var="thrust_curve"       min="0"       step="1"   max="2"  shortname="thrust_curve"/>
       <dl_setting var="temp_mQ_k"       min="0.1"       step="0.1"   max="20"  shortname="temp_mQ_k"/>
       <dl_setting var="ele_min"            min="0"       step="100"   max="6400"  shortname="ele_min"/> 
       <dl_setting var="roll_eff"           min="1"       step="0.05"   max="10"    shortname="roll_eff"/>
       <dl_setting var="yaw_eff"            min="0.1"     step="0.01"   max="1"    shortname="yaw_eff"/>
       <dl_setting var="ele_eff"            min="5"       step="0.5"   max="50"    shortname="ele_eff"/> 
       <dl_setting var="airspeed_fake_on"   min="0"       step="1"     max="1"     values="OFF|ON" shortname="bool_airspeed_fake"/> 
       <dl_setting var="airspeed_fake"      min="0"       step="0.001" max="20"    shortname="airspeed_fake"/>     
     </dl_settings>
   </dl_settings>
  </settings>
  <header>
    <file name="eff_scheduling_rotwing_V2.h"/>
  </header>
  <init fun="eff_scheduling_rotwing_init()"/>
  <periodic fun="eff_scheduling_rotwing_periodic()"/>
  <makefile>
    <file name="eff_scheduling_rotwing_V2.c"/>
    <test firmware="rotorcraft">
      <define name="ROTWING_EFF_SCHED_IXX_BODY" value="1"/>
      <define name="ROTWING_EFF_SCHED_IYY_BODY" value="1"/>
      <define name="ROTWING_EFF_SCHED_IZZ"      value="1"/>
      <define name="ROTWING_EFF_SCHED_IXX_WING" value="1"/>
      <define name="ROTWING_EFF_SCHED_IYY_WING" value="1"/>
      <define name="ROTWING_EFF_SCHED_M"        value="1"/>
      <define name="M_PI"                        value="3.14"/>
      <define name="PERIODIC_FREQUENCY"          value="500.0"/>
      <define name="ACTUATORS_NB"                value="10"/>
      <define name="COMMANDS_NB_PASSIVE"         value="1"/>
      <define name="COMMANDS_NB_VIRTUAL"         value="2"/>
      <define name="COMMANDS_NB_REAL"            value="9"/>
      <define name="COMMANDS_NB_OTHER"           value="2"/>
      <define name="ANDI_OUTPUTS"                value="6"/>
      <define name="EFF_MAT_ROWS_NB"             value="6"/> 
      <define name="EFF_MAT_COLS_NB"             value="11"/>
      <define name="COMMAND_MOTOR_FRONT"         value="0"/>
      <define name="COMMAND_MOTOR_RIGHT"         value="8"/>
      <define name="COMMAND_MOTOR_BACK"          value="9"/>
      <define name="COMMAND_MOTOR_LEFT"          value="3"/>
      <define name="COMMAND_MOTOR_PUSHER"        value="10"/>
      <define name="COMMAND_ELEVATOR"            value="5"/>
      <define name="COMMAND_RUDDER"              value="6"/>
      <define name="COMMAND_AILERONS"            value="7"/>
      <define name="COMMAND_ROT_MECH"            value="11"/>
      <define name="SERVO_ROTATION_MECH_IDX"     value="11"/>
      <define name="RW_aX"                       value="0"/>
      <define name="RW_aY"                       value="1"/>
      <define name="RW_aZ"                       value="2"/>
      <define name="RW_aN"                       value="0"/>
      <define name="RW_aE"                       value="1"/>
      <define name="RW_aD"                       value="2"/>
      <define name="RW_ap"                       value="3"/>
      <define name="RW_aq"                       value="4"/>
      <define name="RW_ar"                       value="5"/>
      <define name="ZERO_ELE_PPRZ"               value="8000"/>
      <define name="ELE_MIN_AS"                  value="8.8"/>
      <define name="ELE_MAX_AS"                  value="16.0"/>
    </test>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/datalink_common.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="datalink_common" dir="datalink" task="datalink">
  <doc>
    <description>
      Common datalink interface for telemetry, downlink and uplink
    </description>
  </doc>
  <header>
    <file name="telemetry.h"/>
    <file name="datalink.h"/>
    <file name="downlink.h"/>
  </header>
  <init fun="datalink_init()"/>
  <init fun="downlink_init()"/>
  <periodic fun="telemetry_reporting_task()"/>
  <periodic fun="datalink_periodic()" freq="1"/>
  <datalink message="ALIVE_REQ" fun="datalink_parse_ALIVE_REQ(dev, trans, buf)"/>
  <datalink message="PING" fun="datalink_parse_PING(dev, trans, buf)"/>
  <makefile>
    <define name="DOWNLINK"/>
    <define name="PERIODIC_TELEMETRY"/>
    <configure name="TELEMETRY_FREQUENCY" default="$(PERIODIC_FREQUENCY)"/>
    <define name="TELEMETRY_FREQUENCY" value="$(TELEMETRY_FREQUENCY)"/>
    <file name="downlink.c"/>
    <file name="datalink.c"/>
    <file name="telemetry.c"/>
    <test firmware="fixedwing">
      <define name="DOWNLINK_TRANSPORT" value="pprz_tp"/>
      <define name="DOWNLINK_DEVICE" value="uart1"/>
      <define name="USE_UART1"/>
    </test>
  </makefile>
  <makefile target="!fbw" firmware="fixedwing">
    <file name="ap_downlink.c" dir="$(SRC_FIRMWARE)"/>
    <test firmware="fixedwing">
      <define name="DOWNLINK_TRANSPORT" value="pprz_tp"/>
      <define name="DOWNLINK_DEVICE" value="uart1"/>
      <define name="USE_UART1"/>
    </test>
  </makefile>
  <makefile firmware="fixedwing">
    <file name="fbw_downlink.c" dir="$(SRC_FIRMWARE)"/>
  </makefile>
  <makefile firmware="rotorcraft">
    <file name="rotorcraft_telemetry.c" dir="$(SRC_FIRMWARE)"/>
    <test firmware="rotorcraft">
      <define name="DOWNLINK_TRANSPORT" value="pprz_tp"/>
      <define name="DOWNLINK_DEVICE" value="uart1"/>
      <define name="USE_UART1"/>
    </test>
  </makefile>
  <makefile firmware="rover">
    <file name="rover_telemetry.c" dir="$(SRC_FIRMWARE)"/>
    <test firmware="rover">
      <define name="DOWNLINK_TRANSPORT" value="pprz_tp"/>
      <define name="DOWNLINK_DEVICE" value="uart1"/>
      <define name="USE_UART1"/>
      <define name="USE_GENERATED_AUTOPILOT"/>
    </test>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/guidance_pid_rotorcraft.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="guidance_pid_rotorcraft" dir="guidance" task="control">
  <doc>
    <description>
      Basic guidance code for rotorcraft with PID control
    </description>
    <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
      <define name="MAX_BANK" value="20" description="maximum commanded bank angle" unit="deg"/>
      <define name="PGAIN" value="79" description="feedback horizontal control P gain"/>
      <define name="DGAIN" value="100" description="feedback horizontal control D gain"/>
      <define name="IGAIN" value="30" description="feedback horizontal control I gain"/>
    </section>
    <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
      <define name="HOVER_KP" value="283" description="feedback vertical control P gain"/>
      <define name="HOVER_KD" value="82" description="feedback vertical control D gain"/>
      <define name="HOVER_KI" value="13" description="feedback vertical control I gain"/>
      <define name="NOMINAL_HOVER_THROTTLE" value="0.655" description="nominal throttle at hover (between 0 and 1)"/>
      <define name="ADAPT_THROTTLE_ENABLED" value="FALSE|TRUE" description="enable adaptive control by default"/>
    </section>
  </doc>
  <settings target="ap|sim|nps">
    <dl_settings>
      <dl_settings NAME="Vert PID">
        <dl_setting var="guidance_pid.v_kp" min="0" step="1" max="600" shortname="kp" param="GUIDANCE_V_HOVER_KP" persistent="true" module="guidance/guidance_pid"/>
        <dl_setting var="guidance_pid.v_kd" min="0" step="1" max="600" shortname="kd" param="GUIDANCE_V_HOVER_KD" persistent="true"/>
        <dl_setting var="guidance_pid.v_ki" min="0" step="1" max="300" shortname="ki" handler="set_v_igain" param="GUIDANCE_V_HOVER_KI" persistent="true" module="guidance/guidance_pid"/>
        <dl_setting var="guidance_pid.adapt_throttle_enabled" min="0" step="1" max="1" shortname="adapt_throttle" param="GUIDANCE_V_ADAPT_THROTTLE_ENABLED" values="FALSE|TRUE" persistent="true"/>
      </dl_settings>
      <dl_settings NAME="Horiz PID">
        <dl_setting var="guidance_pid.approx_force_by_thrust" min="0" step="1" max="1" shortname="approx_force" values="FALSE|TRUE" param="GUIDANCE_H_APPROX_FORCE_BY_THRUST" type="uint8" persistent="true"/>
        <dl_setting var="guidance_pid.kp" min="0" step="1" max="400" shortname="kp" param="GUIDANCE_H_PGAIN" type="int32" persistent="true"/>
        <dl_setting var="guidance_pid.kd" min="0" step="1" max="400" shortname="kd" param="GUIDANCE_H_DGAIN" type="int32" persistent="true"/>
        <dl_setting var="guidance_pid.ki" min="0" step="1" max="400" shortname="ki" handler="set_h_igain" param="GUIDANCE_H_IGAIN" type="int32" persistent="true" module="guidance/guidance_pid"/>
        <dl_setting var="guidance_pid.kv" min="0" step="1" max="400" shortname="kv" param="GUIDANCE_H_VGAIN" type="int32" persistent="true"/>
        <dl_setting var="guidance_pid.ka" min="0" step="1" max="400" shortname="ka" param="GUIDANCE_H_AGAIN" type="int32" persistent="true"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <dep>
    <depends>@stabilization,guidance_rotorcraft</depends>
    <provides>guidance,attitude_command</provides>
  </dep>
  <header>
    <file name="guidance_pid.h"/>
  </header>
  <init fun="guidance_pid_init()"/>
  <makefile target="ap|sim|nps" firmware="rotorcraft">
    <file name="guidance_pid.c" dir="$(SRC_FIRMWARE)/guidance"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/detect_ground_on_landing_am7.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="detect_ground_on_landing_am7" dir="ground_detect">
  <doc>
    <description>
    Detect gound on landing. 
    Provides a function to be called in the flight plan module.
    This module only works together with the AM7 control allocation module. 
    </description>
  </doc>

  <settings>
    <dl_settings>
      <dl_settings NAME="ground_detect">
        <dl_setting var="min_lidar_alt_ground_detect" min="0" step="0.1" max="2" shortname="min_lidar_alt"/>
        <dl_setting var="az_tolerance_land" min="0" step="0.1" max="5" shortname="az_tolerance_land"/>
        <dl_setting var="time_tolerance_land" min="0" step="0.1" max="2" shortname="time_tolerance_land"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <header>
    <file name="ground_detect_am7.h"/>
  </header>
  <init fun="ground_detect_on_landing_am7_init()"/>
  <makefile>
    <file name="ground_detect_am7.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/cv_detect_gate_gd.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="cv_detect_gate_gd" dir="computer_vision">
  <doc>
    <description>
	Detects gates as used in the IROS drone races, i.e., square colored gates. It does so with snake gate detection, a computationally efficient method that works 
	onboard of the computationally constrained Parrot Bebop 1/2 drones.

	An initial version of this algorithm ran in the drone race 2016. The algorithm was first described in:
	
	First autonomous multi-room exploration with an insect-inspired flapping wing vehicle, May 2018, 
	IEEE International Conference on Robotics and Automation (ICRA 2018), Brisbane, Australia
	by Kirk Scheper, Matej Karasek, Christophe De Wagter, Bart Remes, and Guido de Croon
	https://www.researchgate.net/publication/327228053_First_autonomous_multi-room_exploration_with_an_insect-inspired_flapping_wing_vehicle

	For the drone race, the algorithm and performance are described in more detail in:
	Autonomous drone race: A novel vision-based navigation and control strategy,
	S.Li, M.M.O.I. Ozo, C. De Wagter, G.C.H.E. de Croon.
	Submitted.

    </description>
    <!-- <define name="UNDISTORT_MIN_X_NORMALIZED" value="-2.0" description="Minimal normalized x-coordinate to be used for the undistortion"/> --> 
    <define name="DETECT_GATE_FPS" value="0" description="The (maximum) frequency to run the calculations at. If zero, it will max out at the camera frame rate."/>
    <define name="DETECT_GATE_CAMERA" value="bottom_camera|front_camera" description="The V4L2 camera device that is used for the calculations."/>
    <define name="DETECT_GATE_JUST_FILTER" value="FALSE|TRUE" description="Just run a color filter."/>
    <define name="DETECT_GATE_N_SAMPLES" value="10000" description="The number of samples taken in an image for snake gate detection. This number is proportional to the computatinoal effort (more = slower) and the performance (more = better)."/>
    <define name="DETECT_GATE_MIN_PIX_SIZE" value="30" description="The minimal size the sides of an initial (square) detection should have for further processing."/>
    <define name="DETECT_GATE_MIN_GATE_QUALITY" value="0.15" description="Gate quality is checked by verifying the proportion of colored pixels on the gate outline. This is the minimal proportion of colored pixels in order to accept a gate candidate."/>
    <define name="DETECT_GATE_MIN_N_SIDES" value="3" description="How many sides of the gate should have the minimal line quality (min = 0, max = 4)."/>
    <define name="DETECT_GATE_GATE_THICKNESS" value="0.0" description="Snaking goes up and down, and then left and right from the extreme points. If the gate is thick, it is better to start a little bit before the end point. This value is how thick the gate border is as a proportion of the total size."/>
    <define name="DETECT_GATE_Y_MIN" value="20" description="Minimal Y of the color filter."/>
    <define name="DETECT_GATE_Y_MAX" value="228" description="Maximal Y of the color filter."/>
    <define name="DETECT_GATE_U_MIN" value="42" description="Minimal U of the color filter."/>
    <define name="DETECT_GATE_U_MAX" value="121" description="Maximal U of the color filter."/>
    <define name="DETECT_GATE_V_MIN" value="134" description="Minimal V of the color filter."/>
    <define name="DETECT_GATE_V_MAX" value="230" description="Maximal V of the color filter."/>
    <define name="DETECT_GATE_EXCLUDE_PIXELS_TOP" value="0" description="Band on top of the image in which we do not take snake gate samples."/>
    <define name="DETECT_GATE_EXCLUDE_PIXELS_BOTTOM" value="0" description="Band at the bottom of the image in which we do not take snake gate samples."/>
    <define name="DETECT_GATE_SIMPLIFIED_PNP" value="0" description="When set to 0, the full PnP will fit all corners. When set to 1, a simple camera model will be used." />
    <define name="CAMERA_ROTATED_90DEG_RIGHT" value="FALSE" description="If the camera does not have its longest side as horizontal, then the rotated define should be enabled." />
  </doc>

  <settings>
    <dl_settings>
      <dl_settings NAME="Detect gate">
	 <dl_setting var="just_filtering" min="0" step="1" max="1" values="FALSE|TRUE" shortname="just_filter" param="DETECT_GATE_JUST_FILTER"/>
	 <dl_setting var="n_samples"  min="0" step="10" max="10000" shortname="n_samples" param="DETECT_GATE_N_SAMPLES"/> 
	 <dl_setting var="min_px_size"  min="10" step="5" max="500" shortname="min_px" param="DETECT_GATE_MIN_PIX_SIZE"/> 
	 <dl_setting var="min_gate_quality"  min="0.0" step="0.01" max="1.0" shortname="min_qual" param="DETECT_GATE_MIN_GATE_QUALITY"/>
	 <dl_setting var="min_n_sides"  min="0" step="1" max="4" shortname="min_sides" param="DETECT_GATE_MIN_N_SIDES"/> 
	 <dl_setting var="gate_thickness"  min="0.0" step="0.01" max="0.2" shortname="thickness" param="DETECT_GATE_GATE_THICKNESS"/> 
	 <dl_setting var="color_Ym"  min="0" step="1" max="255" shortname="Y_min" param="DETECT_GATE_Y_MIN"/>
	 <dl_setting var="color_YM"  min="0" step="1" max="255" shortname="Y_max" param="DETECT_GATE_Y_MAX"/>
	 <dl_setting var="color_Um"  min="0" step="1" max="255" shortname="U_min" param="DETECT_GATE_U_MIN"/>
	 <dl_setting var="color_UM"  min="0" step="1" max="255" shortname="U_max" param="DETECT_GATE_U_MAX"/>
	 <dl_setting var="color_Vm"  min="0" step="1" max="255" shortname="V_min" param="DETECT_GATE_V_MIN"/>
	 <dl_setting var="color_VM"  min="0" step="1" max="255" shortname="V_max" param="DETECT_GATE_V_MAX"/>
	 <dl_setting var="exclude_top"  min="0" step="1" max="320" shortname="exclude_top" param="DETECT_GATE_EXCLUDE_PIXELS_TOP"/>
	 <dl_setting var="exclude_bottom"  min="0" step="1" max="320" shortname="exclude_bottom" param="DETECT_GATE_EXCCLUDE_PIXELS_BOTTOM"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <dep>
    <depends>video_thread</depends>
  </dep>

  <header>
    <file name="detect_gate_gd.h"/>
  </header>

  <init fun="detect_gate_gd_init()"/>
  <event fun="detect_gate_gd_event()"/>
  <makefile target="ap|nps">
    <file name="detect_gate_gd.c"/>
    <file name="undistortion.c" dir="modules/computer_vision/lib/vision"/>
    <file name="image.c" dir="modules/computer_vision/lib/vision"/>
    <file name="PnP_AHRS.c" dir="modules/computer_vision/lib/vision"/>
    <file name="snake_gate_detection.c" dir="modules/computer_vision"/>    
  </makefile>
  <makefile target="nps">
    <file name="edge_gate_detection.cpp" dir="modules/computer_vision"/>
    <raw>
      nps.CXXFLAGS += $(shell pkg-config --cflags opencv4 || pkg-config --cflags opencv)
      nps.LDFLAGS  += $(shell pkg-config --libs   opencv4 || pkg-config --libs   opencv)
    </raw>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/mavlink.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="mavlink" dir="datalink" task="datalink">
  <doc>
    <description>Basic MAVLink implementation</description>
    <configure name="MAVLINK_PORT" value="UARTx|UDPx|UsbS" description="The port device to use for mavlink (default: UART1)"/>
    <configure name="MAVLINK_BAUD" value="B57600" description="Baud rate if MAVLINK_PORT is a UART"/>
    <define name="MAV_AUTOPILOT_ID" value="MAV_AUTOPILOT_PPZ|MAV_AUTOPILOT_ARDUPILOTMEGA" description="Some MAVLink GCS/Devices require specific ID's to work. Default is to identify as MAV_AUTOPILOT_PPZ."/>
  </doc>
  <settings>
    <dl_settings>
      <dl_settings NAME="mavlink">
        <dl_setting var="mavlink_rc_value" min="0" step="1" max="2500"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <header>
    <file name="mavlink.h"/>
  </header>

  <init fun="mavlink_init()"/>
  <periodic fun="mavlink_periodic()" freq="10" autorun="TRUE"/>
  <periodic fun="mavlink_periodic_telemetry()" autorun="TRUE"/>
  <event fun="mavlink_event()"/>

  <makefile>
    <file name="mavlink.c"/>
    <file name="mission_manager.c" dir="modules/datalink/missionlib"/>
    <!-- <file name="waypoints.c" dir="modules/datalink/missionlib"/> -->
    <!-- <file name="blocks.c" dir="modules/datalink/missionlib"/> -->
    <configure name="MAVLINK_PORT" default="uart1" case="upper|lower"/>
    <configure name="TELEMETRY_FREQUENCY" default="$(PERIODIC_FREQUENCY)"/>
    <define name="TELEMETRY_FREQUENCY" value="$(TELEMETRY_FREQUENCY)"/>
    <raw>
      ifneq (,$(findstring usb,$(MAVLINK_PORT_LOWER)))
      ap.CFLAGS += -DUSE_USB_SERIAL
      ap.srcs += $(SRC_ARCH)/usb_ser_hw.c
      ap.CFLAGS += -DMAVLINK_DEV=usb_serial
      else
      ifneq (,$(findstring udp,$(MAVLINK_PORT_LOWER)))
      include $(CFG_SHARED)/udp.makefile
      $(TARGET).CFLAGS += -DMAVLINK_DEV=$(MAVLINK_PORT_LOWER)
      $(TARGET).CFLAGS += -DUSE_$(MAVLINK_PORT_UPPER)
      else
      MAVLINK_BAUD ?= B57600
      ap.CFLAGS += -DMAVLINK_DEV=$(MAVLINK_PORT_LOWER)
      ap.CFLAGS += -DUSE_$(MAVLINK_PORT_UPPER)
      ap.CFLAGS += -D$(MAVLINK_PORT_UPPER)_BAUD=$(MAVLINK_BAUD)
      endif
      endif
    </raw>
  </makefile>
</module>
