=== tudelft/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (doc,settings_file*,settings*,dep?,header?,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT doc (description,(define|configure|section)*)>
<!ELEMENT settings_file (file*)>
<!ELEMENT settings (dl_settings?)>
<!ELEMENT dep (depends?,conflicts?,provides?,recommends?,suggests?)>
<!ELEMENT depends (#PCDATA)>
<!ELEMENT conflicts (#PCDATA)>
<!ELEMENT provides (#PCDATA)>
<!ELEMENT recommends (#PCDATA)>
<!ELEMENT suggests (#PCDATA)>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|include|flag|file|file_arch|raw|test)*>
<!ELEMENT test (configure|define|include|file|file_arch|shell)*>
<!ELEMENT section (define|configure)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT shell EMPTY>
<!ELEMENT raw (#PCDATA)>
<!ELEMENT dl_settings (dl_setting|dl_settings)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED
task CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST event
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED
class CDATA #IMPLIED
min_len CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST makefile
target CDATA #IMPLIED
firmware CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST section
name CDATA #REQUIRED
prefix CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #IMPLIED
case CDATA #IMPLIED
default CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
integer CDATA #IMPLIED
unit CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST include
name CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST shell
cmd CDATA #REQUIRED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST settings_file
name CDATA #REQUIRED
>

<!ATTLIST settings
name CDATA #IMPLIED
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
header CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ATTLIST test
arch CDATA #IMPLIED
firmware CDATA #IMPLIED
>

=== tudelft/paparazzi/conf/modules/actuators_parrot_minidrone.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="actuators_parrot_minidrone" dir="actuators" task="actuators">
  <doc>
    <description>
      Actuators Driver for a Parrot Minidrone
    </description>
  </doc>
  <dep>
    <depends>actuators</depends>
    <provides>actuators</provides>
  </dep>
  <header>
    <file name="actuators.h" dir="boards/parrot_minidrone"/>
  </header>
  <makefile target="ap">
    <file name="actuators.c" dir="$(SRC_BOARD)"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/rangefinder_adc.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="rangefinder_adc" dir="sensors" task="sensors">
  <doc>
    <description>
    A Rangefinder with an ADC output signal can be used as unidirectional distance sensor. Examples of devices are e.g. Maxbotix MB1210, MB1010 and similar.
    The sensor can be used as a control or measuring tool to detect the range (distance) to a surface, used for example in AGL hold, terrain following or landing assist.

    To be able to use the Rangefinder connected to an ADC input, just add this module in your airframe and set needed parameters.

    Notes:
    + The maximum useful detection distance is 4m for common simple ultrasonic based small sized sensors, even if datasheet e.g. states 7m.
    For most ultrasonic type ADC rangefinder sensor devices, a sampling rate of at least 15Hz is supported. However, if measurements are taken at longer distances, 
    the time required for the ultrasonic pulse to return increases, which may limit the maximum achievable sampling rate. 
    It is recommended to adjust the RANGEFINDER_ADC_PERIODIC_FREQUENCY parameter according to the sensor's capabilities and the expected measurement range to ensure reliable readings.

    + If the distance is read but the scale is incorrect, adjust the RANGEFINDER_ADC_SCALE parameter to match the sensor's specifications.
    The scale factor can also be determined experimentally by measuring a known distance and adjusting the scale until the output matches the expected value. 
    This Scale value adjustment can be performed real-time via the setting panel which make it a little more user friendly.
    After the correct value is determined, save setting or manually add the value to the airframe file.

    RANGEFINDER_ADC_SCALE for common ultrasonicsensors:
    Maxbotix XL-MaxSonar part MB1210 where sensor VCC is 5v: 0.001855
    Maxbotix LV-MaxSonar part MB1010 where sensor VCC is 5v: 0.002315

    + If the sensor is used in an airframe with landing gear, it is recommended to set the RANGEFINDER_ADC_OFFSET to the height of the landing gear, so that the AGL zero value is correct to the ground. 
    Keep in mind that most ultrasonic sensors have a deadzone of 0.15m to 0.25m, so the AGL cannot be measured if landinggear shorter than the deadzone range.

    + There is an option to compensate the AGL value for body rotation, which is useful if e.g. a roll maneuver, the sensor is not pointing straight down it compensates the AGL value for the body rotation.
    
    + Also an option to filter the sensor output is available, which is useful if the sensor is noisy or has a lot of outliers, in case of ultrasonic sensors, almost always the case.
    
    + Distance compensation for pressure and temperature are not implemented, keep in mind that ultrasonic sensors are susceptible to temperature and pressure changes.
    </description>
    <configure name="RANGEFINDER_ADC_PORT" value="ADC_X" description="Set the ADC port the rangefinder sensor is connected to on your flightcontroller, defaults to ADC_3"/>
    <configure name="RANGEFINDER_ADC_USE_FOR_AGL" value="TRUE|FALSE" description="Updates the AGL value in state,if not defined, defaults to FALSE"/>
    <configure name="RANGEFINDER_ADC_COMPENSATE_ROTATION" value="TRUE|FALSE" description="Compensate AGL measurements for body rotation. Disabled by default"/>
    <configure name="RANGEFINDER_ADC_USE_FILTER" value="TRUE|FALSE" description="Enable or disable a filter on the rangefinder output values, defaults to TRUE"/>
    <configure name="RANGEFINDER_ADC_PERIODIC_FREQUENCY" value="30" description="Sensor readings in HZ"/>
    <configure name="RANGEFINDER_ADC_LOWPASS_TAU" value="0.11" description="If filtering is enabled, then one optionally can set this value to filter the output more(or less). Defaults to 0.16"/>
    <configure name="RANGEFINDER_ADC_SCALE" value="0.001789" description="Sensor scale factor [m/adc], defaults to 0.001855"/>
    <define name="USE_SONAR" value="TRUE|FALSE" description="Activate use of rangefinder in INS extended filter (only rotorcraft), defaults to FALSE"/>
    <define name="RANGEFINDER_ADC_OFFSET" value="0.56"  description="Sensor offset in meters, as in where one wants zero to be, default is 0.0"/>
    <define name="RANGEFINDER_ADC_MIN_RANGE" value="0.31" unit="m" description="If defined, set limit to minimum value the sensor can reliably measure, default 0.15m"/>
    <define name="RANGEFINDER_ADC_MAX_RANGE" value="3.1" unit="m" description="If defined, set limit to maximum value the sensor can reliably measure, default 4.0m"/>
    <define name="RANGEFINDER_ADC_SYNC_SEND" value="TRUE|FALSE" description="Send RAW and scaled message with each new measurement,useful for debugging sensor issues (default: FALSE)"/> 
    <define name="RANGEFINDER_ADC_RAW_OFFSET" value="0"  description="sensor offset in [adc] units, defaults to 0"/>
  </doc>
  <settings>
    <dl_settings NAME="Rangefinder">
      <dl_settings NAME="ADC">
        <dl_setting MAX="1" MIN="0" STEP="1" VAR="rangefinder_adc.update_agl" shortname="Update AGL"/>
        <dl_setting MAX="0.006" MIN="0.001" STEP="0.00002" VAR="rangefinder_adc.scale" shortname="Scale"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <dep>
    <depends>adc</depends>
    <provides>sonar</provides>
  </dep>
  <header>
    <file name="rangefinder_adc.h"/>
  </header>
  <init fun="rangefinder_adc_init()"/>
  <periodic fun="rangefinder_adc_periodic()" freq="RANGEFINDER_ADC_PERIODIC_FREQUENCY"/>
  <periodic fun="rangefinder_adc_report()" freq="RANGEFINDER_ADC_PERIODIC_FREQUENCY" autorun="FALSE"/>
  <makefile target="ap">
    <configure name="RANGEFINDER_ADC_PORT" default="ADC_3" case="lower|upper"/>
    <configure name="RANGEFINDER_ADC_USE_FOR_AGL" default="0"/>
    <configure name="RANGEFINDER_ADC_COMPENSATE_ROTATION" default="0"/>
    <configure name="RANGEFINDER_ADC_USE_FILTER" default="1"/>
    <configure name="RANGEFINDER_ADC_PERIODIC_FREQUENCY" default="30"/>
    <configure name="RANGEFINDER_ADC_LOWPASS_TAU" default="0.16"/>
    <configure name="RANGEFINDER_ADC_SCALE" default="0.001855"/>
    <define name="USE_$(RANGEFINDER_ADC_PORT_UPPER)"/>
    <define name="RANGEFINDER_ADC_PORT" value="$(RANGEFINDER_ADC_PORT_UPPER)"/>
    <define name="RANGEFINDER_ADC_USE_FOR_AGL" value="$(RANGEFINDER_ADC_USE_FOR_AGL)"/>
    <define name="RANGEFINDER_ADC_PERIODIC_FREQUENCY" value="$(RANGEFINDER_ADC_PERIODIC_FREQUENCY)"/>
    <define name="RANGEFINDER_ADC_USE_FILTER" value="$(RANGEFINDER_ADC_USE_FILTER)"/>
    <file name="rangefinder_adc.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/pn.xml
<!DOCTYPE module SYSTEM "module.dtd">
 
<module name="pn">
<doc>
    <description>
    Guidance controller for rotorcraft 
    </description>
</doc>
<header>
    <file name="pn.h"/>
</header>
<init fun="pn_init()"/>
<periodic fun="pn_run()" freq="50" start="pn_start()"
 		    stop="pn_stop()" autorun="FALSE"/>
<event fun="pn_event()"/>
<datalink message="REMOTE_GPS_LOCAL" fun="pn_parse_REMOTE_GPS_LOCAL(buf)"/>
<makefile target="ap|nps">
    <configure name="MODEM_DEV" default="UDP0" case="upper|lower"/>
    <file name="pn.c"/>
    <file name="pprz_transport.c" dir="pprzlink/src"/>
    <define name="DOWNLINK_DEVICE" value="$(MODEM_DEV_LOWER)"/>
</makefile>
</module>

=== tudelft/paparazzi/conf/modules/green_attractor.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="green_attractor">
  <doc>
    <description>
This module is written by mavCourse 2022 group 2. It was inspired by the orange_avoider.
This module is used in combination with a color filter (cv_detect_color_object) and the navigation mode of the autopilot.
The avoidance strategy is to simply count the total number of green pixels (track floor). When below a certain percentage threshold,
(given by color_count_frac) we assume that there is an obstacle and we turn.

The color filter settings are set using the cv_detect_color_object. This module can run multiple filters simultaneously
so you have to define which filter to use with the ORANGE_AVOIDER_VISUAL_DETECTION_ID setting.
    </description>
    <!-- maybe skip changing the msg stuff to green_attractor -->
    <define name="ORANGE_AVOIDER_VISUAL_DETECTION_ID" value="ABI_BROADCAST" description="which VISUAL_DETECTION message to recieve for orange pole detection."/>
  </doc>
    <settings>
    <dl_settings>
      <dl_settings name="GreenAttractor">
         <dl_setting var="oa_color_count_frac" min="0" step="0.01" max="1.0"/>
         <dl_setting var="meander_frac" min="0" step="0.01" max="1.0"/>
         <dl_setting var="meander_increment" min="0" step="1" max="20"/>
      </dl_settings>
    </dl_settings>
  </settings>
  
  <dep>
    <depends>cv_detect_color_object</depends>
  </dep>
  <header>
    <file name="green_attractor.h"/>
  </header>
  <init fun="green_attractor_init()"/>
  <periodic fun="green_attractor_periodic()" freq="4"/> <!-- tweak -->
  <periodic fun="log_distance_covered_periodic()" freq="1"/>
  <makefile target="ap|nps">
    <file name="green_attractor.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/terrain.xml
<!DOCTYPE module SYSTEM "module.dtd">
<module name="terrain" dir="terrain">
  <doc>
    <description>
      Provides functionality to get from a coordinate the height of terrain in respect to AMSL 
      The data is retrieved from terrain data files stored on onboard storage e.g. SD card.
      The files to generates should be compatible with AP .DAT format.
    </description>
    <configure name="TERRAIN_DATA_DIR" value="/TERRAIN" description="Directory for terrain DAT files"/>
  </doc>
  <header>
    <file name="terrain.h"/>
  </header>
  <init fun="terrain_init()"/>
  <makefile>
    <file name="terrain.c"/>
    <configure name="TERRAIN_DATA_DIR" default="/TERRAIN"/>
    <define name="TERRAIN_DATA_DIR" value="$(TERRAIN_DATA_DIR)" type="string"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/gps_ublox.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="gps_ublox" dir="gps" task="sensors">
  <doc>
    <description>
      U-blox GPS (UART)
      Driver for u-blox GPS modules parsing the binary UBX protocol.
      
      The reset variable allows us to manually restart the u-blox GPS. There are three modes:
        - Hotstart  (GPS_UBX_BOOTRESET = 1)
        - Warmstart (GPS_UBX_BOOTRESET = 2)
        - Coldstart (GPS_UBX_BOOTRESET = 3) 
    </description>
    <configure name="UBX_GPS_PORT" value="UARTx" description="UART where the GPS is connected to (UART1, UART2, etc"/>
    <configure name="UBX_GPS_BAUD" value="B38400" description="UART baud rate"/>
    <configure name="GPS_UBX_BOOTRESET" value="0" description="Force a hot, warm or cold reset when the system boot up"/>
  </doc>

  <settings>
    <dl_settings>
      <dl_settings name="gps_ublox">
        <dl_setting MIN="1" MAX="3" STEP="1" values="Hotstart|Warmstart|Coldstart" module="gps/gps_ubx" VAR="gps_ubx_reset" shortname="reset"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <dep>
    <depends>uart,gps</depends>
    <provides>gps</provides>
  </dep>
  <header>
    <file name="gps.h"/>
  </header>
  <init fun="gps_ubx_init()"/>
  <periodic fun="gps_ubx_periodic_check()" freq="1." autorun="TRUE"/>
  <event fun="gps_ubx_event()"/>
  <datalink message="HITL_UBX" fun="gps_ubx_parse_HITL_UBX(buf)"/> 
  <makefile target="ap|fbw">
    <file name="gps_ubx.c"/>

    <!-- GPS Ublox 1 -->
    <configure name="UBX_GPS_PORT" default="$(GPS_PORT)" case="upper|lower"/>
    <configure name="UBX_GPS_BAUD" default="$(GPS_BAUD)"/>
    <define name="USE_$(UBX_GPS_PORT_UPPER)"/>
    <define name="UBX_GPS_PORT" value="$(UBX_GPS_PORT_LOWER)"/>
    <define name="$(UBX_GPS_PORT_UPPER)_BAUD" value="$(UBX_GPS_BAUD)"/>

    <!-- GPS Ublox 2 -->
    <configure name="UBX2_GPS_PORT" default="$(GPS2_PORT)" case="upper|lower"/>
    <configure name="UBX2_GPS_BAUD" default="$(GPS2_BAUD)"/>
    <define name="USE_$(UBX2_GPS_PORT_UPPER)" cond="ifneq ($(UBX2_GPS_PORT)$(SECONDARY_GPS),)"/>
    <define name="UBX2_GPS_PORT" value="$(UBX2_GPS_PORT_LOWER)" cond="ifneq ($(UBX2_GPS_PORT)$(SECONDARY_GPS),)"/>
    <define name="$(UBX2_GPS_PORT_UPPER)_BAUD" value="$(UBX2_GPS_BAUD)" cond="ifneq ($(UBX2_GPS_BAUD)$(SECONDARY_GPS),)"/>
    <define name="GPS_UBX_NB" value="2" cond="ifneq ($(UBX2_GPS_PORT)$(SECONDARY_GPS),)"/>
    <raw>
      ifdef SECONDARY_GPS
        ifneq (,$(findstring ublox2, $(SECONDARY_GPS)))
          # this is the secondary GPS
          $(TARGET).CFLAGS += -DGPS_SECONDARY_TYPE_H=\"modules/gps/gps_ubx.h\"
          $(TARGET).CFLAGS += -DSECONDARY_GPS=GPS_UBX2
          $(TARGET).CFLAGS += -DGPS_UBX_NB=2
        else ifneq (,$(findstring ublox, $(SECONDARY_GPS)))
          # this is the secondary GPS
          $(TARGET).CFLAGS += -DGPS_SECONDARY_TYPE_H=\"modules/gps/gps_ubx.h\"
          $(TARGET).CFLAGS += -DSECONDARY_GPS=GPS_UBX
        endif

        ifneq (,$(findstring ublox2, $(PRIMARY_GPS)))
          $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/gps/gps_ubx.h\"
          $(TARGET).CFLAGS += -DPRIMARY_GPS=GPS_UBX2
          $(TARGET).CFLAGS += -DGPS_UBX_NB=2
        else ifneq (,$(findstring ublox, $(PRIMARY_GPS)))
          $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/gps/gps_ubx.h\"
          $(TARGET).CFLAGS += -DPRIMARY_GPS=GPS_UBX
        endif
      else
        # plain old single GPS usage
        $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/gps/gps_ubx.h\"
      endif
    </raw>
    <test>
      <define name="PRIMARY_GPS" value="GPS_UBX"/>
      <define name="USE_UART2"/>
      <define name="UBX_GPS_PORT" value="uart2"/>
    </test>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/flap_wiggle.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="flap_wiggle" dir="ctrl">
  <doc>
    <description>
      Module to move flaps independently of control commands
    </description>
  </doc>
  <settings>
    <dl_settings>
      <dl_settings NAME="flap_wiggle">
        <dl_setting var="flap_wiggle_state" min="0" step="1" max="1" shortname="state" values="OFF|ON" type="bool"/>
        <dl_setting var="flap_wiggle_gain" min="0.0" step="10" max="9000" shortname="gain" type="float"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <header>
    <file name="flap_wiggle.h"/>
  </header>
  <init fun="flap_wiggle_init()"/>
  <periodic fun="flap_wiggle_periodic()" freq="500"/>
  <makefile>
    <file name="flap_wiggle.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/precision_landing.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
  Precision Landing Module for Fixed-Wing Aircraft
  ================================================
  This module controls automated final approach, predictive crow braking (spoileron drag),
  and safety-gated go-around logic for target touchdown waypoint landing.

  End-User Quick Start:
  - Requires rangefinder module (e.g. agl_dist / Surertech VB22A) and pitot (SDP33).
  - Main tuning parameters during field test:
      * BRAKE_GAIN: Increase (e.g. 0.08 -> 0.12) if aircraft floats too far past TD.
      * BRAKE_ENABLE_AGL: Altitude (m) where laser prediction starts controlling crow.
      * FLARE_AGL: Altitude (m) where fixed pitch flare begins (configured in flight plan).
-->
<module name="precision_landing" dir="nav">
  <doc>
    <description>
      Fixed-Wing Autonomous Precision Landing System.
      Predicts touchdown point using 2D GNSS position/velocity and rangefinder AGL height.
      Commands bounded crow braking and rejects unsuitable approaches above commit height.
      Experimental: prediction is not an accuracy or flight-safety guarantee.
      Explicit start in AUTO2 is required after pilot takeover. Flare does not change
      the global throttle-kill flag. Real sensor and aerodynamic validation is required.
      RC and GCS mode changes must use the autopilot mode setter, never direct assignments.
      The example validates live parameters and geometry before navigation. Its crow bench
      test requires fresh near-ground range, near-zero motion, no launch and killed throttle.
    </description>
    
    <!-- Airspeed Safety Limits -->
    <define name="MIN_AIRSPEED" value="8.2" unit="m/s" description="Minimum safe approach airspeed. Braking is disengaged if airspeed falls below this margin to prevent stall."/>
    <define name="AIRSPEED_TIMEOUT" value="0.5" unit="s" description="Maximum air-data sample age authorizing braking in final or flare."/>
    <define name="APPROACH_CORRIDOR_SLOPE" value="0.25" description="Extra lateral corridor width per meter above brake_agl; converges to MAX_CROSS_TRACK."/>
    
    <!-- Precision Boundary Limits (Abort Triggers) -->
    <define name="MAX_CROSS_TRACK" value="1.2" unit="m" description="Maximum allowable lateral drift from runway centerline (leaves 0.3m safety margin inside official 1.5m half-box)."/>
    <define name="MAX_LONG_ERROR" value="8.0" unit="m" description="Maximum allowable longitudinal prediction error before confirming an abort."/>
    <define name="MAX_AIM_DISTANCE" value="20.0" unit="m" description="Maximum upstream glide aim, independent of the unchanged touchdown rejection limits. This geometric intercept is not a predicted stopping distance."/>
    <define name="REJECT_DELAY" value="0.2" unit="s" description="Persistence time requirement for boundary violation before triggering go-around (filters sensor noise)."/>
    
    <!-- Altitude & Decision Bands -->
    <define name="BRAKE_ENABLE_AGL" value="4.0" unit="m" description="Highest rangefinder AGL height (m) where close-range predictive crow braking engages."/>
    <define name="ABORT_AGL" value="2.5" unit="m" description="No-powered-abort latch height. Fresh AGL takes precedence; unknown height is conservative. Normal flare height is separate."/>
    <define name="AGL_TIMEOUT" value="0.25" unit="s" description="Maximum age of rangefinder measurement before falling back to barometric altitude."/>
    
    <!-- Filter & Controller Gains -->
    <define name="MIN_SINK_RATE" value="0.25" unit="m/s" description="Minimum sink rate floor to prevent numerical division-by-zero during time-to-ground projection."/>
    <define name="AGL_RATE_TAU" value="0.15" unit="s" description="Time constant for rangefinder sink rate low-pass filter (balances noise filtering with flare response)."/>
    <define name="BRAKE_GAIN" value="0.08" description="Proportional gain converting predicted overshoot meters to crow brake demand."/>
    <define name="MAX_BRAKE" value="1.0" description="Maximum allowed total crow brake command (1.0 = 100% full spoileron deflection)."/>
    <define name="UPPER_MAX_BRAKE" value="0.5" description="Maximum allowed crow brake command in upper barometric altitude band (50% preserves pitch control)."/>
    
    <!-- Touchdown Flare Constraints -->
    <define name="FLARE_MAX_ROLL" value="8.0" unit="deg" description="Maximum roll setpoint allowed during flare to prevent wingtip strikes on belly-landing foam planes."/>
  </doc>
  
  <dep>
    <depends>agl_dist,air_data</depends>
  </dep>
  
  <header>
    <file name="precision_landing.h"/>
  </header>
  
  <init fun="precision_landing_init()"/>
  
  <makefile target="ap|nps|sim">
    <define name="USE_PRECISION_LANDING" value="TRUE"/>
    <file name="precision_landing.c"/>
  </makefile>
</module>
