=== tudelft/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (doc,settings_file*,settings*,dep?,header?,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT doc (description,(define|configure|section)*)>
<!ELEMENT settings_file (file*)>
<!ELEMENT settings (dl_settings?)>
<!ELEMENT dep (depends?,conflicts?,provides?,recommends?,suggests?)>
<!ELEMENT depends (#PCDATA)>
<!ELEMENT conflicts (#PCDATA)>
<!ELEMENT provides (#PCDATA)>
<!ELEMENT recommends (#PCDATA)>
<!ELEMENT suggests (#PCDATA)>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|include|flag|file|file_arch|raw|test)*>
<!ELEMENT test (configure|define|include|file|file_arch|shell)*>
<!ELEMENT section (define|configure)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT shell EMPTY>
<!ELEMENT raw (#PCDATA)>
<!ELEMENT dl_settings (dl_setting|dl_settings)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED
task CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST event
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED
class CDATA #IMPLIED
min_len CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST makefile
target CDATA #IMPLIED
firmware CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST section
name CDATA #REQUIRED
prefix CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #IMPLIED
case CDATA #IMPLIED
default CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
integer CDATA #IMPLIED
unit CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST include
name CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST shell
cmd CDATA #REQUIRED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST settings_file
name CDATA #REQUIRED
>

<!ATTLIST settings
name CDATA #IMPLIED
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
header CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ATTLIST test
arch CDATA #IMPLIED
firmware CDATA #IMPLIED
>

=== tudelft/paparazzi/conf/modules/vutura_utm_interface.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="vutura_utm_interface" dir="vutura">
  <doc>
    <description>Sends over position and speed data to vutura utm module</description>
  </doc>
  <header>
    <file name="vutura_utm_interface.h"/>
  </header>
  <init fun="init_vutura_utm_interface()"/>
  <periodic fun="parse_gps()" freq="4"/>
  <event fun="avoid_check()"/>
  <event fun="RunAvoidance()"/>
  <makefile>
    <file name="vutura_utm_interface.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/nn_divergence_landing.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="nn_divergence_landing">
  <doc>
    <description>Neural network landing</description>
  </doc>

  <settings>
    <dl_settings>
      <dl_settings NAME="NN Landing">
        <dl_setting var="thrust_effectiveness" min="0" step="0.05" max="2"/>
        <dl_setting var="nn_thrust_p_gain" min="0" step="0.05" max="2"/>
        <dl_setting var="nn_thrust_i_gain" min="0" step="0.05" max="2"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <header>
    <file name="nn.h"/>
  </header>
  <init fun="nn_init()"/>
  <periodic fun="nn_periodic()" freq="2" autorun="FALSE"/>
  <event fun="nn_cntrl()"/>
  <makefile target="ap|nps">
    <file name="nn.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/serial_act_t4.xml
<!DOCTYPE module SYSTEM "module.dtd">
<module name="serial_act_t4" dir="sensors">
  <doc>
    <description>Fly by wire module on Teensy 4.0</description>
  </doc>

  <settings>
    <dl_settings>
      <dl_settings NAME="FBW Control">
        <dl_setting var="cl_ailerons_slider"  min="0" step=".01" max="0.5" shortname="cl_ailerons_slider" persistent="true"/>
        <dl_setting var="ailerons_first_order_num"  min="0" step=".01" max="0.5" shortname="ailerons_first_order_num" persistent="true"/>
        <dl_setting var="K_indi_rad_s_dshot"  min="0" step=".1" max="20" shortname="K_indi_rad_s_dshot" persistent="true"/>
        <dl_setting var="test_rpm_control" min="0" step="1" max="1" shortname="test_rpm_control" values="FALSE|TRUE" persistent="true"/>
        <dl_setting var="motor_1_rad_s_slider" min="0" step="1" max="2000" shortname="motor_1_rad_s" persistent="true"/>
        <dl_setting var="motor_2_rad_s_slider" min="0" step="1" max="2000" shortname="motor_2_rad_s" persistent="true"/>
        <dl_setting var="motor_3_rad_s_slider" min="0" step="1" max="2000" shortname="motor_3_rad_s" persistent="true"/>
        <dl_setting var="motor_4_rad_s_slider" min="0" step="1" max="2000" shortname="motor_4_rad_s" persistent="true"/>
        <dl_setting var="test_dshot_cmd" min="0" step="1" max="1" shortname="test_dshot_cmd" values="FALSE|TRUE" persistent="true"/>
        <dl_setting var="motor_1_dshot_slider" min="0" step="1" max="2000" shortname="motor_1_dshot" persistent="true"/>
        <dl_setting var="motor_2_dshot_slider" min="0" step="1" max="2000" shortname="motor_2_dshot" persistent="true"/>
        <dl_setting var="motor_3_dshot_slider" min="0" step="1" max="2000" shortname="motor_3_dshot" persistent="true"/>
        <dl_setting var="motor_4_dshot_slider" min="0" step="1" max="2000" shortname="motor_4_dshot" persistent="true"/>
        <dl_setting var="test_servo_angles" min="0" step="1" max="1" shortname="test_servo_angles" values="FALSE|TRUE" persistent="true"/>
        <dl_setting var="el_1_angle_deg_slider" min="-180" step="1" max="180" shortname="el_1_angle_deg" persistent="true"/>
        <dl_setting var="el_2_angle_deg_slider" min="-180" step="1" max="180" shortname="el_2_angle_deg" persistent="true"/>
        <dl_setting var="el_3_angle_deg_slider" min="-180" step="1" max="180" shortname="el_3_angle_deg" persistent="true"/>
        <dl_setting var="el_4_angle_deg_slider" min="-180" step="1" max="180" shortname="el_4_angle_deg" persistent="true"/>
        <dl_setting var="az_1_angle_deg_slider" min="-180" step="1" max="180" shortname="az_1_angle_deg" persistent="true"/>
        <dl_setting var="az_2_angle_deg_slider" min="-180" step="1" max="180" shortname="az_2_angle_deg" persistent="true"/>
        <dl_setting var="az_3_angle_deg_slider" min="-180" step="1" max="180" shortname="az_3_angle_deg" persistent="true"/>
        <dl_setting var="az_4_angle_deg_slider" min="-180" step="1" max="180" shortname="az_4_angle_deg" persistent="true"/>
        <dl_setting var="flaperon_right_angle_deg_slider" min="-90" step="1" max="90" shortname="flaperon_right_angle_deg" persistent="true"/>
        <dl_setting var="flaperon_left_angle_deg_slider" min="-90" step="1" max="90" shortname="flaperon_left_angle_deg" persistent="true"/>
        <dl_setting var="min_pwm_servo_9" min="0" step="1" max="2500" shortname="min_pwm_servo_9" persistent="true"/>
        <dl_setting var="neutral_pwm_servo_9" min="0" step="1" max="2500" shortname="neutral_pwm_servo_9" persistent="true"/>
        <dl_setting var="max_pwm_servo_9" min="0" step="1" max="2500" shortname="max_pwm_servo_9" persistent="true"/>
        <dl_setting var="min_pwm_servo_10" min="0" step="1" max="2500" shortname="min_pwm_servo_10" persistent="true"/>
        <dl_setting var="neutral_pwm_servo_10" min="0" step="1" max="2500" shortname="neutral_pwm_servo_10" persistent="true"/>
        <dl_setting var="max_pwm_servo_10" min="0" step="1" max="2500" shortname="max_pwm_servo_10" persistent="true"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <header>
    <file name="serial_act_t4.h"/>
  </header>
  <init fun="serial_act_t4_init()"/>
  <periodic fun="serial_act_t4_control()" autorun="TRUE" freq="SERIAL_ACT_T4_FREQUENCY"/>
  <event fun="serial_act_t4_event()"/>
  

  <makefile>
    <!-- Configure default UART port and baudrate-->
    <configure name="SERIAL_ACT_T4_PORT" default="UART4" case="upper|lower"/>
    <configure name="SERIAL_ACT_T4_BAUD" default="B921600"/>
    <!-- Enable UART and set baudrate -->
    <define name="USE_$(SERIAL_ACT_T4_PORT_UPPER)" value="TRUE"/>
    <define name="USE_$(SERIAL_ACT_T4_PORT_UPPER)_TX" value="TRUE"/>
    <define name="$(SERIAL_ACT_T4_PORT_UPPER)_BAUD" value="$(SERIAL_ACT_T4_BAUD)"/>
    <define name="SERIAL_ACT_T4_PORT" value="$(SERIAL_ACT_T4_PORT_LOWER)"/>
    <file name="serial_act_t4.c" dir="modules/sensors"/>
    <file name="pprz_transport.c" dir="pprzlink/src"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/imu_aspirin_v2_common.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="imu_aspirin_v2_common" dir="imu" task="sensors">
  <doc>
    <description>
      Common functionality of Aspirin v2 IMUs. The Aspirin IMU can be used on different flight controllers. 
      Most commonly used onboard a Lisa M(X) v2.1 FC, but IMU can be connected over SPI to other flight controllers as well. 
      The Aspirin IMU consists of:
      - Accelerometer and Gyro: MPU6000 connected over SPI.
      - Magnetometer: HMC5883 as I2C slave of the MPU6000 Acc/gyro.
      - Barometer: ms5611 connected over SPI as well, but this is not handled by this module, but by the barometer module.
    </description>
    <configure name="ASPIRIN_2_SPI_DEV" value="spi2" description="SPI device to use for for the IMU sensor"/>
    <configure name="ASPIRIN_2_SPI_SLAVE_IDX" value="SPI_SLAVE2" description="On which slave index the IMU is connected"/>
    <define name="ASPIRIN_2_DISABLE_MAG" value="FALSE" description="set to TRUE to disable the mag on Aspirin"/>
    <define name="ASPIRIN_2_ROTATED_180_DEG" value="FALSE" description="set to TRUE if IMU is 180 degrees rotated on Z axis on Aspirin IMU, default is False"/>
    
    <section name="IMU" prefix="IMU_">
      <define name="MAG_X_NEUTRAL" value="2350"/>
      <define name="MAG_Y_NEUTRAL" value="2350"/>
      <define name="MAG_Z_NEUTRAL" value="2100"/>

      <define name="MAG_X_SENS" value="3.50" integer="16"/>
      <define name="MAG_Y_SENS" value="3.60" integer="16"/>
      <define name="MAG_Z_SENS" value="4.90" integer="16"/>
    </section>
  </doc>
  <dep>
    <depends>spi_master,imu_common</depends>
    <provides>imu,mag</provides>
  </dep>
  <header>
    <file name="imu_aspirin_2_spi.h"/>
  </header>
  <init fun="imu_aspirin2_init()"/>
  <periodic fun="imu_aspirin2_periodic()"/>
  <event fun="imu_aspirin2_event()"/>
  <makefile target="!sim|nps|fbw">
    <configure name="ASPIRIN_2_SPI_DEV" default="spi2" case="lower|upper"/>
    <configure name="ASPIRIN_2_SPI_SLAVE_IDX" default="SPI_SLAVE2"/>

    <define name="ASPIRIN_2_SPI_DEV" value="$(ASPIRIN_2_SPI_DEV_LOWER)"/>
    <define name="USE_$(ASPIRIN_2_SPI_DEV_UPPER)"/>
    <define name="ASPIRIN_2_SPI_SLAVE_IDX" value="$(ASPIRIN_2_SPI_SLAVE_IDX)"/>
    <define name="USE_$(ASPIRIN_2_SPI_SLAVE_IDX)"/>

    <file name="mpu60x0.c" dir="peripherals"/>
    <file name="mpu60x0_spi.c" dir="peripherals"/>
    <file name="imu_aspirin_2_spi.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/rangefinder_pwm.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="rangefinder_pwm" dir="sensors" task="sensors">
  <doc>
    <description>
    Driver for a PWM based rangefinder sensor
    Reads sensor using PWM input and outputs rangefinder distance to object in [m]

    Notes:
    + The maximum useful detection distance is 4m for common rangefinder PWM output signal small sized sensors, even if datasheet e.g. states 7m.
    For most PWM of the ultrasonic type of devices, a sampling rate of at least 10Hz is supported. However, if measurements are taken at longer distances, 
    the time required for the ultrasonic pulse to return increases, which may limit the maximum achievable sampling rate. 
    It is recommended to adjust the RANGEFINDER_PWM_PERIODIC_FREQUENCY parameter according to the sensor's capabilities and the expected measurement range to ensure reliable readings.
    For laser type of sensors, usually much higher sampling rates are possible, light just is a tad bit faster than sound.

    + If the distance is read but the scale is incorrect, adjust the RANGEFINDER_PWM_SCALE parameter to match the sensor's specifications.
    The scale factor can also be determined experimentally by measuring a known distance and adjusting the scale until the output matches the expected value.

    + If the sensor is used in an airframe with landing gear, it is recommended to set the RANGEFINDER_PWM_OFFSET to the length of the landing gear, so that the AGL value is correct. 
    Keep in mind that most ultrasonic type of sensors have a deadzone of 0.15m to 0.25m, so the AGL cannot be measured if landinggear is shorter than the deadzone range.

    + There is an option to compensate the AGL value for body rotation, which is useful if e.g. a roll maneuver, the sensor is not pointing straight down it compensates the AGL value for the body rotation.
    
    + Also an option to filter the sensor output is available, which is useful if the sensor is noisy or has a lot of outliers, in case of a sonar type sensors, almost always the case.
    Lidar type of sensors are usually less noisy and have less outliers, so filtering better be disabled.
    
    Why choose PWM sensor over ADC sensor:
    One only needs to connect GND, VCC and one more signal wire, same as ADC but not the disadvantages of ADC sensors noise

    PWM Sensor example: Maxbotix LV-EZ1
    </description>
    <configure name="RANGEFINDER_PWM_PORT" value="PWM_INPUTx" description="Select PWM input port on flightcontroller for sensor to use e.g. PWM_INPUT1"/>
    <configure name="RANGEFINDER_PWM_USE_FOR_AGL" value="TRUE|FALSE" description="Updates the AGL value in state,if not defined, defaults to FALSE"/>
    <configure name="RANGEFINDER_PWM_COMPENSATE_ROTATION" value="TRUE|FALSE" description="Compensate AGL measurements for body rotation. Disabled by default"/>
    <configure name="RANGEFINDER_PWM_PERIODIC_FREQUENCY" value="30" description="Sensor readings in HZ"/>
    <define name="RANGEFINDER_PWM_USE_FILTER" value="TRUE|FALSE" description="If this is enabled, a median filter on the distance output, defaults to TRUE"/>
    <define name="RANGEFINDER_PWM_MEDIAN_SIZE" value="11" description="If median filter is enabled then set this option to filter the output more(or less), default is 7"/>
    <define name="RANGEFINDER_PWM_SCALE" value="0.00006" description="Sensor scale for raw sensor output to a meter unit conversion, "/>
    <define name="RANGEFINDER_PWM_OFFSET" value="0.56" description="Sensor offset in meters, as in where one wants zero to be for e.g. landinggear to ground, default is 0.0"/>
    <define name="RANGEFINDER_PWM_MIN_RANGE" value="0.44" unit="m" description="If defined, set limit to minimum value the sensor can reliably measure, default 0.25m"/>
    <define name="RANGEFINDER_PWM_MAX_RANGE" value="2.2" unit="m" description="If defined, set limit to maximum value the sensor can reliably measure, default 7.0m"/>
    <define name="RANGEFINDER_PWM_SYNC_SEND" value="TRUE|FALSE" description="Send RAW and scaled message with each new measurement,useful for debugging sensor issues (default: FALSE)"/>
    <define name="RANGEFINDER_PWM_PWM_PERIOD" value="4096" description="period in microsec (e.g. 4096 for 12 bits sensor)"/>
    <define name="RANGEFINDER_PWM_PWM_OFFSET" value="320" description="initial offset on the raw pwm signal if needed (default: 820usec). Do not confuse this with RANGEFINDER_PWM_OFFSET"/>
  </doc>

  <dep>
    <depends>pwm_meas</depends>
    <provides>sonar</provides>
  </dep>
  <header>
    <file name="rangefinder_pwm.h" />
  </header>
  <init fun="rangefinder_pwm_init()" />
  <periodic fun="rangefinder_pwm_read()" freq="RANGEFINDER_PWM_PERIODIC_FREQUENCY" />
  <!-- <periodic fun="rangefinder_periodic_report()" freq="10" autorun="FALSE"/> -->
  <makefile target="ap|nps|sim">
    <file name="rangefinder_pwm.c"/>
  </makefile>
  <makefile target="ap">
    <!-- <configure name="RANGEFINDER_PWM_PORT" value="$(RANGEFINDER_PWM_PORT)"/> -->
    <configure name="RANGEFINDER_PWM_USE_FOR_AGL" default="0"/>
    <configure name="RANGEFINDER_PWM_COMPENSATE_ROTATION" default="0"/>
    <configure name="RANGEFINDER_PWM_PERIODIC_FREQUENCY" default="30"/>
    <define name="RANGEFINDER_PWM_PORT" value="$(RANGEFINDER_PWM_PORT)" cond="ifdef RANGEFINDER_PWM_PORT"/>
    <define name="$(RANGEFINDER_PWM_PORT)_TICKS_PER_USEC" value="1" />
    <define name="USE_$(RANGEFINDER_PWM_PORT)" value="PWM_PULSE_TYPE_ACTIVE_LOW" />
    <define name="RANGEFINDER_PWM_USE_FOR_AGL" value="$(RANGEFINDER_PWM_USE_FOR_AGL)"/>
    <!-- <define name="RANGEFINDER_PWM_SCALE" value="$(RANGEFINDER_PWM_SCALE)"/> -->
    <define name="RANGEFINDER_PWM_COMPENSATE_ROTATION" value="$(RANGEFINDER_PWM_COMPENSATE_ROTATION)"/>
    <define name="RANGEFINDER_PWM_PERIODIC_FREQUENCY" value="$(RANGEFINDER_PWM_PERIODIC_FREQUENCY)"/>
    <file name="rangefinder_pwm.c"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/baro_spa06.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="baro_spa06" dir="sensors" task="sensors">
  <doc>
    <description>
     SPA06/SPL06 pressure sensor (I2C or SPI)
    </description>
    <configure name="SPA06_USE_SPI" default="FALSE" description="select which bus type use (default I2C -> FALSE, SPI -> TRUE)"/>
    <configure name="SPA06_DEV" value="i2cX/spiX" description="select which i2c/spi peripheral to use (default i2c1/spi1)"/>
    <configure name="SPA06_SLAVE_IDX" value="spi_slave0" description="select which slave peripheral to use when bus is spi (default spi_slave0)"/>
    <define name="SPA06_SLAVE_ADDR" value="SPA06_I2C_ADDR|SPA06_I2C_ADDR_ALT" description="i2c slave address (default SPA06_I2C_ADDR)"/>
    <define name="SPA06_SYNC_SEND" description="flag to transmit the data as it is acquired, good for debugging only"/>
  </doc>
  <dep>
    <depends>i2c|spi_master</depends>
    <provides>baro</provides>
  </dep>
  <header>
    <file name="baro_spa06.h"/>
  </header>
  <init fun="baro_spa06_init()"/>
  <periodic fun="baro_spa06_periodic()" freq="25"/>
  <event fun="baro_spa06_event()"/>
  <makefile target="ap" >
    <configure name="SPA06_USE_SPI" default="FALSE"/>
    <define name="SPA06_USE_SPI" value="$(SPA06_USE_SPI)" />
    <file name="baro_spa06.c"/>
    <file name="spa06.c" dir="peripherals"/>
    <test>
      <define name="SPA06_USE_SPI"/>
      <define name="SPA06_DEV" value="spi1"/>
      <define name="SPA06_SLAVE_IDX" value="0"/>
      <define name="SPI_MASTER"/>
      <define name="USE_SPI1"/>
    </test>
    <test>
      <define name="SPA06_DEV" value="i2c1"/>
      <define name="USE_I2C1"/>
    </test>
  </makefile>
  <makefile target="ap" cond="ifeq ($(SPA06_USE_SPI), TRUE)">
    <configure name="SPA06_DEV" default="spi1" case="upper|lower"/>
    <configure name="SPA06_SLAVE_IDX" default="spi_slave0" case="upper|lower"/>
    <define name="USE_$(SPA06_DEV_UPPER)"/>
    <define name="SPA06_DEV" value="$(SPA06_DEV_LOWER)"/>
    <define name="SPA06_SLAVE_IDX" value="$(SPA06_SLAVE_IDX_UPPER)" />
    <define name="USE_$(SPA06_SLAVE_IDX_UPPER)" />
  </makefile>
  <makefile target="ap" cond="ifeq ($(SPA06_USE_SPI), FALSE)">
    <configure name="SPA06_DEV" default="i2c1" case="upper|lower"/>
    <configure name="SPA06_SLAVE_ADDR" default="SPA06_I2C_ADDR"/>
    <define name="USE_$(SPA06_DEV_UPPER)"/>
    <define name="SPA06_DEV" value="$(SPA06_DEV_LOWER)"/>
  </makefile>
</module>

=== tudelft/paparazzi/conf/modules/MAV_cv_detect_group12_cmjong.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="MAV_cv_detect_group12_cmjong" dir="computer_vision">
  <doc>
    <description>Color Object Detector
    Detects an object by a continuous color. Optionally draws on image.
    
    </description>
    <define name="COLOR_OBJECT_DETECTOR_CAMERA" value="front_camera" description="Video device to use"/>
    <define name="ORANGE_OBJECT_DETECTOR_FPS" value="0" description="Desired FPS (0: camera rate)"/>
    <define name="ORANGE_OBJECT_DETECTOR_LUM_MIN" value="0" description="Min luminance"/>
    <define name="ORANGE_OBJECT_DETECTOR_LUM_MAX" value="0" description="Max luminance"/>
    <define name="ORANGE_OBJECT_DETECTOR_CB_MIN" value="0" description="Min blue chroma"/>
    <define name="ORANGE_OBJECT_DETECTOR_CB_MAX" value="0" description="Max blue chroma"/>
    <define name="ORANGE_OBJECT_DETECTOR_CR_MIN" value="0" description="Min red chroma"/>
    <define name="ORANGE_OBJECT_DETECTOR_CR_MAX" value="0" description="Max red chroma"/>
    
    <define name="BLUE_OBJECT_DETECTOR_CAMERA" value="front_camera"/>
    <define name="BLUE_OBJECT_DETECTOR_FPS" value="0"/>
    <define name="BLUE_OBJECT_DETECTOR_LUM_MIN" value="0"/>
    <define name="BLUE_OBJECT_DETECTOR_LUM_MAX" value="0"/>
    <define name="BLUE_OBJECT_DETECTOR_CB_MIN" value="0"/>
    <define name="BLUE_OBJECT_DETECTOR_CB_MAX" value="0"/>
    <define name="BLUE_OBJECT_DETECTOR_CR_MIN" value="0"/>
    <define name="BLUE_OBJECT_DETECTOR_CR_MAX" value="0"/>

    <define name="GREEN_OBJECT_DETECTOR_CAMERA" value="front_camera"/>
    <define name="GREEN_OBJECT_DETECTOR_FPS" value="0"/>
    <define name="GREEN_OBJECT_DETECTOR_LUM_MIN" value="0"/>
    <define name="GREEN_OBJECT_DETECTOR_LUM_MAX" value="0"/>
    <define name="GREEN_OBJECT_DETECTOR_CB_MIN" value="0"/>
    <define name="GREEN_OBJECT_DETECTOR_CB_MAX" value="0"/>
    <define name="GREEN_OBJECT_DETECTOR_CR_MIN" value="0"/>
    <define name="GREEN_OBJECT_DETECTOR_CR_MAX" value="0"/>

    <define name="COLOR_OBJECT_DETECTOR_DRAW" value="FALSE|TRUE" description="Draw detection on image"/>
    <define name="GREEN_OBJECT_DETECTOR_DRAW" value="FALSE|TRUE" description="Force green mask drawing from plant detector"/>

    <define name="WEIGHT_ORANGE_DETECTOR" value="0"/>
    <define name="WEIGHT_GREEN_DETECTOR" value="0"/>
    <define name="WEIGHT_OPTICAL_FLOW" value="0"/>


  </doc>

  <settings>
    <dl_settings>
      <dl_settings name="ColorObjectDetector">
         <dl_setting var="orange_lum_min" min="0" step="1" max="255" shortname="y_orange_min"/>
         <dl_setting var="orange_lum_max" min="0" step="1" max="255" shortname="y_orange_max"/>
         <dl_setting var="orange_cb_min"  min="0" step="1" max="255" shortname="u_orange_min"/>
         <dl_setting var="orange_cb_max"  min="0" step="1" max="255" shortname="u_orange_max"/>
         <dl_setting var="orange_cr_min"  min="0" step="1" max="255" shortname="v_orange_min"/>
         <dl_setting var="orange_cr_max"  min="0" step="1" max="255" shortname="v_orange_max"/>
         <dl_setting var="blue_lum_min" min="0" step="1" max="255" shortname="y_blue_min"/>
         <dl_setting var="blue_lum_max" min="0" step="1" max="255" shortname="y_blue_max"/>
         <dl_setting var="blue_cb_min"  min="0" step="1" max="255" shortname="u_blue_min"/>
         <dl_setting var="blue_cb_max"  min="0" step="1" max="255" shortname="u_blue_max"/>
         <dl_setting var="blue_cr_min"  min="0" step="1" max="255" shortname="v_blue_min"/>
         <dl_setting var="blue_cr_max"  min="0" step="1" max="255" shortname="v_blue_max"/>
         <dl_setting var="green_lum_min" min="0" step="1" max="255" shortname="y_green_min"/>
         <dl_setting var="green_lum_max" min="0" step="1" max="255" shortname="y_green_max"/>
         <dl_setting var="green_cb_min"  min="0" step="1" max="255" shortname="u_green_min"/>
         <dl_setting var="green_cb_max"  min="0" step="1" max="255" shortname="u_green_max"/>
         <dl_setting var="green_cr_min"  min="0" step="1" max="255" shortname="v_green_min"/>
         <dl_setting var="green_cr_max"  min="0" step="1" max="255" shortname="v_green_max"/>
         <dl_setting var="cod_draw"  min="0" step="1" max="1" values="False|True" shortname="draw 1" />

      </dl_settings>
    </dl_settings>
  </settings>

  <settings>
    <dl_settings>
      <dl_settings name="Weigth_of_detectors">
         <dl_setting var="weight_orange_detector" min="0" step="0.01" max="1" shortname="W_orange_d"/>
         <dl_setting var="weight_green_detector" min="0" step="0.01" max="1" shortname="W_green_d"/>
         <dl_setting var="weight_optical_flow" min="0" step="0.01" max="1" shortname="W_optical_f"/>
      </dl_settings>
    </dl_settings>
  </settings>



  <dep>
    <depends>video_thread,MAV_plant_avoider</depends>
  </dep>

  <header>
    <file name="MAV_cv_detect_group12_cmjong.h"/>
  </header>

  <init fun="MAV_cv_detect_group12_cmjong_init()"/>
  <periodic fun="MAV_cv_detect_group12_cmjong_periodic()" freq="50"/>
  <makefile target="ap|nps">
    <file name="MAV_cv_detect_group12_cmjong.c"/>
    <file name="MAV_cv_color_group12_cmjong.c"/>  
  </makefile>
</module>
