=== tudelft/paparazzi/conf/autopilot/autopilot.dtd
<!-- Paparazzi Autopilot DTD -->

<!ELEMENT autopilot (state_machine+)>
<!ELEMENT state_machine (modules*,includes?,settings*,control_block*,mode_selection?,exceptions?,mode*)>
<!ELEMENT control_block (call*)>
<!ELEMENT mode_selection (mode_select*)>
<!ELEMENT exceptions (exception*)>
<!ELEMENT includes (include*,define*)>
<!ELEMENT mode (select*,on_enter?,control*,exception*,on_exit?)>
<!ELEMENT select EMPTY>
<!ELEMENT mode_select EMPTY>
<!ELEMENT on_enter (call|call_block)*>
<!ELEMENT on_exit (call|call_block)*>
<!ELEMENT control (call|call_block)*>
<!ELEMENT exception EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_block EMPTY>
<!ELEMENT modules (module)*>
<!ELEMENT module (configure|define)*>
<!ELEMENT define EMPTY>
<!ELEMENT configure EMPTY>
<!ELEMENT settings (dl_setting*)>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST autopilot
name CDATA #IMPLIED>

<!ATTLIST state_machine
name CDATA #REQUIRED
freq CDATA #REQUIRED
gcs_mode CDATA #IMPLIED
settings_mode CDATA #IMPLIED
settings_handler CDATA #IMPLIED>

<!ATTLIST control_block
name CDATA #REQUIRED>

<!ATTLIST mode
name CDATA #REQUIRED
shortname CDATA #IMPLIED
gcs_name CDATA #IMPLIED
settings CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST includes>

<!ATTLIST mode_selection>

<!ATTLIST select
cond CDATA #REQUIRED
exception CDATA #IMPLIED>

<!ATTLIST mode_select
cond CDATA #REQUIRED
mode CDATA #REQUIRED
exception CDATA #IMPLIED>

<!ATTLIST on_enter>
<!ATTLIST on_exit>
  
<!ATTLIST control
freq CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST include
name CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
cond CDATA #IMPLIED
store CDATA #IMPLIED>

<!ATTLIST call_block
name CDATA #REQUIRED>

<!ATTLIST modules>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED
target CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

=== tudelft/paparazzi/conf/autopilot/rotorcraft_rotwing_ANDI_INDI.xml
<!DOCTYPE autopilot SYSTEM "autopilot.dtd">

<autopilot name="Rotating Wing Autopilot">

  <state_machine name="ap" freq="PERIODIC_FREQUENCY" gcs_mode="true" settings_mode="true" settings_handler="autopilot_generated|SetModeHandler">

    <modules>
      <!-- <module name="nav" type="rotorcraft"/>
      <module name="guidance" type="rotorcraft"/>
      <module name="stabilization" type="rotorcraft"/> -->
      <module name="rotwing_ap_utils"/>
    </modules>

    <includes>
      <include name="generated/airframe.h"/>
      <include name="autopilot.h"/>
      <include name="autopilot_rc_helpers.h"/>
      <include name="modules/radio_control/radio_control.h"/>
      <include name="modules/gps/gps.h"/>
      <include name="modules/actuators/actuators.h"/>
      <include name="modules/nav/ground_detect.h"/>

      <!-- Failsafe variables -->
      <define name="NO_GPS_LOST_WITH_DATALINK_TIME" value="20" cond="ifndef NO_GPS_LOST_WITH_DATALINK_TIME"/>
      <define name="NO_GPS_LOST_WITH_RC_VALID" value="FALSE" cond="ifndef NO_GPS_LOST_WITH_RC_VALID"/>
      <define name="RC_LOST_MODE" value="AP_MODE_NAV" cond="ifndef RC_LOST_MODE"/>
      <define name="FAILSAFE_DESCENT_SPEED" value="1.0" cond="ifndef FAILSAFE_DESCENT_SPEED"/>

      <!-- Modes -->
      <define  name="MODE_MANUAL"    value="AP_MODE_ATTITUDE_DIRECT"  cond="ifndef MODE_MANUAL"/>
      <define  name="MODE_AUTO2"     value="AP_MODE_NAV"              cond="ifndef MODE_AUTO2"/>
      <define  name="RCLost()"       value="(radio_control.status != RC_OK)"/> <!-- !=RC_OK might be a little strict -->
      <define  name="DLModeNav()"    value="(autopilot_mode_auto2 == AP_MODE_NAV)"/>
      <define  name="DLModeGuided()" value="(autopilot_mode_auto2 == AP_MODE_GUIDED)"/>
      <define  name="DLModeModule()" value="(MODE_AUTO1 == AP_MODE_MODULE)"/>
      <define  name="DLModeAZH()"    value="(MODE_AUTO1 == AP_MODE_ATTITUDE_Z_HOLD)"/>
      <define  name="SetThrottleValue()"    value="autopilot.throttle = commands[COMMAND_THRUST];"/>
    </includes>

    <settings>
      <dl_setting var="autopilot.kill_throttle" min="0" step="1" max="1" module="autopilot" values="Resurrect|Kill" handler="KillThrottle"/>
      <dl_setting var="autopilot_mode_auto2" min="2" step="1" max="3" module="autopilot" values="NAV|GUIDED"/>
    </settings>

    <control_block name="set_commands">
      <call fun="SetRotorcraftCommands(stabilization.cmd, autopilot_in_flight(), autopilot_get_motors_on())"/>
      <call fun="SetThrottleValue()"/>
    </control_block>

    <control_block name="run_indi_att_control">
      <call fun="guidance_v_run(autopilot_in_flight())" store="struct ThrustSetpoint thrust_sp"/>
      <call fun="stabilization_indi_attitude_run(autopilot_in_flight(), &stabilization.rc_sp, &thrust_sp, stabilization.cmd)"/>
    </control_block>

    <control_block name="run_rate_control">
      <call fun="guidance_v_run(autopilot_in_flight())" store="struct ThrustSetpoint thrust_sp"/>
      <call fun="stabilization_run(autopilot_in_flight(), &stabilization.rc_sp, &thrust_sp, stabilization.cmd)"/>
    </control_block>

    <!-- Enter blocks different controllers -->
    <control_block name="indi_enter">
      <call fun="guidance_indi_enter()"/>
      <call fun="stabilization_indi_enter()"/>
    </control_block>

    <control_block name="andi_enter">
      <call fun="oneloop_andi_enter(false, CTRL_ANDI)"/>
    </control_block>

    <!-- Periodic blocks different controllers -->
    <control_block name="run_andi_attitude_control">
      <call fun="guidance_oneloop_run_mode(autopilot_in_flight(), &guidance_h, &guidance_v, rotwing_ap.h_mode, rotwing_ap.v_mode)"/>
      <call fun="guidance_v_run(autopilot_in_flight())" store="struct ThrustSetpoint thrust_sp"/>
    </control_block>

    <control_block name="run_indi_control">
      <call fun="guidance_indi_run_mode(autopilot_in_flight(), &guidance_h, &guidance_v, rotwing_ap.h_mode, rotwing_ap.v_mode)" store="struct StabilizationSetpoint stab_sp"/>
      <call fun="guidance_v_run(autopilot_in_flight())" store="struct ThrustSetpoint thrust_sp"/>
      <call fun="stabilization_indi_attitude_run(autopilot_in_flight(), &stab_sp, &thrust_sp, stabilization.cmd)"/>
    </control_block>

    <control_block name="update_v_sp_gcs">
      <call fun="guidance_v_set_z(-nav.nav_altitude)"/>
      <call fun="guidance_h_set_pos(nav.carrot.y, nav.carrot.x)"/>
    </control_block>

    <exceptions>
      <exception cond="nav.too_far_from_home" deroute="HOME"/>
      <exception cond="kill_switch_is_on()" deroute="KILL"/>
    </exceptions>

    <!-- Kill throttle mode 0-->
    <mode name="KILL">
      <select cond="kill_switch_is_on()"/>
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NONE)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_NONE, 0)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_KILL)"/>
        <call fun="autopilot_set_in_flight(false)"/>
        <call fun="autopilot_set_motors_on(false)"/>
        <call fun="stabilization.cmd[COMMAND_THRUST] = 0"/>
      </on_enter>
      <control>
        <call fun="SetCommands(commands_failsafe)"/>
      </control>
    </mode>

    <!-- Failsafe mode 1-->
    <mode name="FAILSAFE" shortname="FAIL">
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NONE)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_CLIMB)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_ATTITUDE, STABILIZATION_ATT_SUBMODE_HEADING)"/>
        <call fun="guidance_v_set_vz(FAILSAFE_DESCENT_SPEED)"/>
        <call fun="NavStartDetectGround()"/>
      </on_enter>
      <control>
        <call fun="NavVerticalThrottleMode(MAX_PPRZ*(0.5))"/>
        <call fun="stabilization_get_failsafe_sp()" store="struct StabilizationSetpoint stab_failsafe"/>
        <call fun="guidance_v_run(autopilot_in_flight())" store="struct ThrustSetpoint thrust_sp"/>
        <call fun="stabilization_run(autopilot_in_flight(), &stab_failsafe, &thrust_sp, stabilization.cmd)"/>
        <call_block name="set_commands"/>
      </control>
      <exception cond="!GpsIsLost() && !(agl_dist_valid && agl_dist_value_filtered < 5.0)" deroute="$LAST_MODE"/>
      <exception cond="NavDetectGround()" deroute="Kill"/>
      <exception cond="!nav_is_in_flight()" deroute="Kill"/>
      <exception cond="ground_detect()" deroute="Kill"/>
    </mode>

    <!-- Home mode 2-->
    <mode name="HOME">
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NAV)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_NAV)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_ATTITUDE, STABILIZATION_ATT_SUBMODE_HEADING)"/>
      </on_enter>
      <control freq="NAVIGATION_FREQUENCY">
        <call fun="nav_home()"/>
      </control>
      <control>
        <call_block name="run_indi_control"/>
        <call_block name="set_commands"/>
      </control>
      <exception cond="GpsIsLost() && autopilot_in_flight() && !NO_GPS_LOST_WITH_RC_VALID && (datalink_time > NO_GPS_LOST_WITH_DATALINK_TIME)" deroute="FAILSAFE"/>
    </mode>

    <!-- Rate mode 3-->
    <mode name="RATE_DIRECT" shortname="RATE">
      <!-- <select cond=""/> -->
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NONE)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_RC_DIRECT)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_RATE, 0)"/>
      </on_enter>
      <control freq="NAVIGATION_FREQUENCY">
        <call fun="nav_periodic_task()"/>
      </control>
      <control>
        <call_block name="run_rate_control"/>
        <call_block name="set_commands"/>
      </control>
      <exception cond="RCLost()" deroute="NAV"/>
    </mode>

    <!-- Attitude mode 4-->
    <mode name="ATTITUDE_DIRECT" shortname="ATT_QUAD">
      <select cond="RCMode0()"/>
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NONE)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_RC_DIRECT)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_ATTITUDE, STABILIZATION_ATT_SUBMODE_HEADING)"/>
      </on_enter>
      <control freq="NAVIGATION_FREQUENCY">
        <call fun="nav_periodic_task()"/>
      </control>
      <control>
        <call_block name="run_indi_att_control"/>
        <call_block name="set_commands"/>
      </control>
      <exception cond="RCLost()" deroute="NAV"/>
    </mode>

    <!-- NAV: 13 -->
    <mode name="NAV">
      <select cond="RCMode2() && DLModeNav()" exception="HOME"/>
      <select cond="$DEFAULT_MODE"/>
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NAV)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_NAV)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_ATTITUDE, STABILIZATION_ATT_SUBMODE_HEADING)"/>
        <call_block name="indi_enter"/>
      </on_enter>
      <control freq="NAVIGATION_FREQUENCY">
        <call fun="nav_periodic_task()"/>
      </control>
      <control>
        <call_block name="run_indi_control"/>
        <call_block name="update_v_sp_gcs"/>
        <call_block name="set_commands"/>
      </control>
      <exception cond="GpsIsLost() && autopilot_in_flight() && !NO_GPS_LOST_WITH_RC_VALID && (datalink_time > NO_GPS_LOST_WITH_DATALINK_TIME)" deroute="FAILSAFE"/>
      <exception cond="rotwing_ap.ctrl_mode == ROTWING_CTRL_MODE_ANDI" deroute="NAV_ANDI"/>
    </mode>

    <!-- FORWARD: 16 -->
    <mode name="FORWARD" shortname="FW">
      <select cond="RCMode1()"/>
      <on_enter>
        <call fun="guidance_h_mode_changed(GUIDANCE_H_MODE_NONE)"/>
        <call fun="guidance_v_mode_changed(GUIDANCE_V_MODE_RC_DIRECT)"/>
        <call fun="stabilization_mode_changed(STABILIZATION_MODE_ATTITUDE, STABILIZATION_ATT_SUBMODE_FORWARD)"/>
      </on_enter>
      <control freq="NAVIGATION_FREQUENCY">
        <call fun="nav_periodic_task()"/>
      </control>
      <control>
