=== tudelft/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (header?,waypoints,sectors?,variables?,modules?,includes?,exceptions?,blocks)>

<!ELEMENT procedure (param*,header?,waypoints?,sectors?,exceptions?,blocks?)>

<!ELEMENT header (#PCDATA)>

<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT sectors (sector|kml)*>
<!ELEMENT sector (corner,corner,corner+)>
<!ELEMENT corner EMPTY>
<!ELEMENT kml EMPTY>

<!ELEMENT variables (variable|abi_binding)*>
<!ELEMENT variable EMPTY>
<!ELEMENT abi_binding EMPTY>

<!ELEMENT modules (module*)>
<!ELEMENT module  (configure|define)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>

<!ELEMENT includes (include*)>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|home|path|guided)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path|guided)*>
<!ELEMENT for (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path|guided)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_once EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT home EMPTY>
<!ELEMENT eight EMPTY>
<!ELEMENT oval EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT path EMPTY>
<!ELEMENT guided EMPTY>


<!ATTLIST flight_plan
name CDATA #REQUIRED
lat0 CDATA #REQUIRED
lon0 CDATA #REQUIRED
max_dist_from_home CDATA #REQUIRED
ground_alt CDATA #REQUIRED
security_height CDATA #REQUIRED
alt CDATA #REQUIRED
wp_frame CDATA #IMPLIED
qfu CDATA #IMPLIED
home_mode_height CDATA #IMPLIED
geofence_max_alt CDATA #IMPLIED
geofence_max_height CDATA #IMPLIED
geofence_sector CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST sectors>

<!ATTLIST sector
name CDATA #REQUIRED
color CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST corner
name CDATA #REQUIRED>

<!ATTLIST kml
file CDATA #REQUIRED>

<!ATTLIST variables>

<!ATTLIST variable
var CDATA #REQUIRED
type CDATA #IMPLIED
init CDATA #IMPLIED
shortname CDATA #IMPLIED
min CDATA #IMPLIED
max CDATA #IMPLIED
step CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED>

<!ATTLIST abi_binding
name CDATA #REQUIRED
vars CDATA #IMPLIED
id CDATA #IMPLIED
handler CDATA #IMPLIED>

<!ATTLIST modules>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST blocks>

<!ATTLIST block
name CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
on_enter CDATA #IMPLIED
on_exit CDATA #IMPLIED
strip_button CDATA #IMPLIED
strip_icon CDATA #IMPLIED
group CDATA #IMPLIED
key CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST for
var CDATA #REQUIRED
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST heading
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST go
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST path
wpts CDATA #REQUIRED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
until CDATA #IMPLIED
loop CDATA #IMPLIED
break CDATA #IMPLIED>

<!ATTLIST call_once
fun CDATA #REQUIRED
break CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED>

<!ATTLIST xyz
radius CDATA #IMPLIED>

<!ATTLIST home>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
height CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST eight
center CDATA #REQUIRED
turn_around CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
until CDATA #IMPLIED
radius CDATA #REQUIRED>


<!ATTLIST oval
p1 CDATA #REQUIRED
p2 CDATA #REQUIRED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
orientation CDATA #IMPLIED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST guided
commands CDATA #REQUIRED
flags CDATA #IMPLIED
until CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST includes>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST param
name CDATA #REQUIRED
default_value CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST return
reset_stage CDATA #IMPLIED>

=== tudelft/paparazzi/conf/flight_plans/tudelft/cargodrone_valkenburg.xml
<?xml version="1.0"?>
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">
<flight_plan alt="60" ground_alt="0" lat0="52.168595" lon0="4.412444" max_dist_from_home="5000" name="Nederdrone Valkenburg" security_height="2">
  <header>
    #include "autopilot.h"
    #include "modules/datalink/datalink.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="12.6" y="-48.7"/>
    <waypoint name="CLIMB" x="62.6" y="-80.4"/>
    <waypoint name="STDBY" x="106.0" y="-55.1"/>
    <waypoint name="p1" x="298.634" y="-260.614"/>
    <waypoint name="p2" x="696.0" y="-148.1"/>
    <waypoint name="p3" x="600.4" y="73.4"/>
    <waypoint name="p4" x="238.6" y="-48.5"/>
    <waypoint name="TD" x="-4.1" y="-23.7"/>
    <!-- <waypoint name="FOLLOW" x="123.2" y="-87.8"/> -->
    <waypoint name="l1" lat="52.1685507" lon="4.4123303" alt="20"/>
    <waypoint name="l2" lat="52.1662956" lon="4.4135311" alt="0"/>
    <waypoint lat="52.169189" lon="4.410820" name="C1"/>
    <waypoint lat="52.168049" lon="4.406923" name="C2"/>
    <waypoint lat="52.166515" lon="4.408235" name="C3"/>
    <waypoint lat="52.163255" lon="4.407668" name="C4"/>
    <waypoint lat="52.161908" lon="4.410082" name="C5"/>
    <waypoint lat="52.162641" lon="4.416992" name="C6"/>
    <waypoint lat="52.164861" lon="4.427268" name="C7"/>
    <waypoint lat="52.170422" lon="4.427511" name="C8"/>
    <waypoint lat="52.172276" lon="4.424011" name="C9"/>
  </waypoints>
  <sectors>
    <sector color="red" name="Flyzone">
      <corner name="C1"/>
      <corner name="C2"/>
      <corner name="C3"/>
      <corner name="C4"/>
      <corner name="C5"/>
      <corner name="C6"/>
      <corner name="C7"/>
      <corner name="C8"/>
      <corner name="C9"/>
    </sector>
  </sectors>
  <variables>
    <variable var="gear_pitch" init="-50" type="float" min="-90.0" max="0." step="1.0"/>
    <variable var="takeoff_thrust" init="0.85" type="float" min="0." max="1.0" step="0.01"/>
  </variables>
  <modules>
    <!--module name="follow_me"/-->
    <module name="nav" type="survey_rectangle_rotorcraft">
      <define name="RECTANGLE_SURVEY_DEFAULT_SWEEP" value="100"/>
    </module>
  </modules>
  <exceptions>
    <exception cond="Or(!InsideFlyzone(GetPosX(), GetPosY()), GetPosAlt() @GT GetAltRef() + 1500) @AND !(nav_block == IndexOfBlock('Wait GPS')) @AND !(nav_block == IndexOfBlock('Geo init')) @AND !(nav_block == IndexOfBlock('Holding point'))" deroute="Holding point"/>
    <exception cond="datalink_time @GT 25 @AND !(nav_block == IndexOfBlock('Wait GPS')) @AND !(nav_block == IndexOfBlock('Geo init')) @AND !(nav_block == IndexOfBlock('Holding point')) @AND !(nav_block == IndexOfBlock('Standby'))" deroute="Standby"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid() || !state.ned_initialized_i"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Start Engine" strip_button="Takeoff" strip_icon="takeoff.png">
      <set value="FALSE" var="agl_inflight"/>
      <set value="FALSE" var="force_forward"/>
      <set value="DegOfRad(stateGetNedToBodyEulers_f()->theta)" var="gear_pitch"/>
      <call_once fun="waypoint_set_xy_i(WP_CLIMB,POS_BFP_OF_REAL(GetPosX()+100.0*sinf(stateGetNedToBodyEulers_f()->psi)),POS_BFP_OF_REAL(GetPosY()+100.0*cosf(stateGetNedToBodyEulers_f()->psi)))"/>
      <call_once fun="NavResurrect()"/>
      <call_once fun="nav_set_heading_current()"/>
      <attitude pitch="gear_pitch" roll="0" throttle="0.0" until="stage_time @GT 1" vmode="throttle"/>
    </block>
    <block name="Rolling Phase">
      <exception cond="GetPosHeight() @GT 5.0" deroute="Climb"/>
      <call_once fun="nav_set_heading_current()"/>
      <attitude pitch="gear_pitch" roll="0" throttle="takeoff_thrust" vmode="throttle"/>
    </block>
    <block name="Climb">
      <exception cond="GetPosHeight() @GT 30.0" deroute="Oval"/>
      <call_once fun="nav_set_heading_current()"/>
      <go climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
      <deroute block="Oval"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <set value="FALSE" var="force_forward"/>
      <stay wp="STDBY"/>
    </block>
    <block name="stay_p1">
      <set value="FALSE" var="force_forward"/>
      <stay wp="p1"/>
    </block>
    <block name="go_p2">
      <set value="TRUE" var="force_forward"/>
      <go wp="p2"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="line_p1_p2">
      <set value="TRUE" var="force_forward"/>
      <go from="p1" hmode="route" wp="p2"/>
      <stay until="stage_time @GT 10" wp="p2"/>
      <go from="p2" hmode="route" wp="p1"/>
      <deroute block="line_p1_p2"/>
    </block>
    <block name="route">
      <set value="TRUE" var="force_forward"/>
      <go from="p1" hmode="route" wp="p2"/>
      <go from="p2" hmode="route" wp="p3"/>
      <go from="p3" hmode="route" wp="p4"/>
      <go from="p4" hmode="route" wp="p1"/>
      <deroute block="route"/>
    </block>
    <block name="Oval">
      <set value="TRUE" var="force_forward"/>
      <oval p1="p1" p2="p2" radius="nav.radius"/>
    </block>
    <block name="landing line l1 l2">
      <set value="TRUE" var="force_forward"/>
      <go wp="l1"/>
      <go from="l1" hmode="route" wp="l2" vmode="climb" climb="nav.descend_vspeed"/>
      <stay wp="l2"/>
    </block>
    <block name="land here" strip_button="Land Here" strip_icon="land-right.png">
      <set value="FALSE" var="force_forward"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
    </block>
    <block name="land">
      <set value="FALSE" var="force_forward"/>
      <go wp="TD"/>
    </block>
    <block name="descend">
      <set value="FALSE" var="force_forward"/>
      <exception cond="LessThan(GetPosHeight(), 15.0)" deroute="flare"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="flare">
      <set value="FALSE" var="force_forward"/>
      <stay climb="-0.5" vmode="climb" wp="TD"/>
    </block>
    <block name="landed">
      <set value="FALSE" var="force_forward"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== tudelft/paparazzi/conf/flight_plans/tudelft/Altura_TUDelft_FP.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="8" ground_alt="0" lat0="51 59 27.6" lon0="4 22 42.0" max_dist_from_home="1000" name="Delft Basic" security_height="5">
  <header>
    #include "autopilot.h"
    #include "subsystems/datalink/datalink.h"
    #include "subsystems/radio_control.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0.0" y="0.0"/>
    <waypoint name="CLIMB" x="0.0" y="5.0"/>
    <waypoint name="STDBY" x="-2.0" y="-5.0"/>
    <waypoint name="p1" x="-11.7" y="1.6"/>
    <waypoint name="p2" x="6.2" y="9.2"/>
    <waypoint name="p3" x="20.0" y="-16.3"/>
    <waypoint name="p4" x="-0.8" y="-25.1"/>
    <waypoint name="TD" x="5.6" y="-10.9"/>
    <waypoint name="HGF1" x="-92.6" y="60.7"/>
    <waypoint name="HGF2" x="-20.1" y="-96.0"/>
    <waypoint name="HGF3" x="114.9" y="-33.3"/>
    <waypoint name="HGF4" x="21.3" y="103.7"/>
    <waypoint name="SGF1" x="-48.4" y="34.3"/>
    <waypoint name="SGF2" x="-5.7" y="-52.6"/>
    <waypoint name="SGF3" x="46.5" y="-35.7"/>
    <waypoint name="SGF4" x="3.4" y="52.7"/>
  </waypoints>
  <sectors>
    <sector color="red" name="HardGeofence">
      <corner name="HGF1"/>
      <corner name="HGF2"/>
      <corner name="HGF3"/>
      <corner name="HGF4"/>
    </sector>
    <sector color="yellow" name="SoftGeofence">
      <corner name="SGF1"/>
      <corner name="SGF2"/>
      <corner name="SGF3"/>
      <corner name="SGF4"/>
    </sector>
  </sectors>
  <exceptions>
    <exception cond="Or(!InsideHardGeofence(GetPosX(), GetPosY()), GetPosAlt() > GetAltRef() + 100) && !(nav_block == IndexOfBlock('Wait GPS')) && !(nav_block == IndexOfBlock('Geo init')) && !(nav_block == IndexOfBlock('Holding point'))" deroute="Holding point"/>
    <exception cond="Or(!InsideSoftGeofence(GetPosX(), GetPosY()), GetPosAlt() > GetAltRef() + 100) && !(nav_block == IndexOfBlock('Wait GPS')) && !(nav_block == IndexOfBlock('Geo init')) && !(nav_block == IndexOfBlock('Holding point'))" deroute="Standby"/>
    <exception cond="And(radio_control.status == RC_REALLY_LOST, datalink_time > 25) && !(nav_block == IndexOfBlock('Wait GPS')) && !(nav_block == IndexOfBlock('Geo init')) && !(nav_block == IndexOfBlock('Holding point'))" deroute="land"/>
    <exception cond="datalink_time > 20 && !(nav_block == IndexOfBlock('Wait GPS')) && !(nav_block == IndexOfBlock('Geo init')) && !(nav_block == IndexOfBlock('Holding point')) && !(nav_block == IndexOfBlock('Standby'))" deroute="Standby"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetGroundReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="stateGetPositionEnu_f()->z > 2.0" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="2.0" vmode="climb" wp="CLIMB"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <stay wp="STDBY"/>
    </block>
    <block name="stay_p1">
      <stay wp="p1"/>
    </block>
    <block name="go_p2">
      <go wp="p2"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="line_p1_p2">
      <go from="p1" hmode="route" wp="p2"/>
      <stay until="stage_time>10" wp="p2"/>
      <go from="p2" hmode="route" wp="p1"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="route">
      <go from="p1" hmode="route" wp="p2"/>
      <go from="p2" hmode="route" wp="p3"/>
      <go from="p3" hmode="route" wp="p4"/>
      <go from="p4" hmode="route" wp="p1"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="land here" strip_button="Land Here" strip_icon="land-right.png">
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
    </block>
    <block name="land">
      <go wp="TD"/>
    </block>
    <block name="descend">
      <exception cond="!(stateGetPositionEnu_f()->z > 15.0)" deroute="flare"/>
      <stay climb="-1.5" vmode="climb" wp="TD"/>
    </block>
    <block name="flare">
      <stay climb="-0.4" vmode="climb" wp="TD"/>
      <exception cond="!(stateGetPositionEnu_f()->z > 2.0)" deroute="flare_low"/>
    </block>
    <block name="flare_low">
      <exception cond="NavDetectGround()" deroute="Holding point"/>
      <exception cond="!nav_is_in_flight()" deroute="landed"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="-0.4" vmode="climb" wp="TD"/>
    </block>
    <block name="landed">
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>
