=== tudelft/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (header?,waypoints,sectors?,variables?,modules?,includes?,exceptions?,blocks)>

<!ELEMENT procedure (param*,header?,waypoints?,sectors?,exceptions?,blocks?)>

<!ELEMENT header (#PCDATA)>

<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT sectors (sector|kml)*>
<!ELEMENT sector (corner,corner,corner+)>
<!ELEMENT corner EMPTY>
<!ELEMENT kml EMPTY>

<!ELEMENT variables (variable|abi_binding)*>
<!ELEMENT variable EMPTY>
<!ELEMENT abi_binding EMPTY>

<!ELEMENT modules (module*)>
<!ELEMENT module  (configure|define)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>

<!ELEMENT includes (include*)>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|home|path|guided)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path|guided)*>
<!ELEMENT for (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path|guided)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_once EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT home EMPTY>
<!ELEMENT eight EMPTY>
<!ELEMENT oval EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT path EMPTY>
<!ELEMENT guided EMPTY>


<!ATTLIST flight_plan
name CDATA #REQUIRED
lat0 CDATA #REQUIRED
lon0 CDATA #REQUIRED
max_dist_from_home CDATA #REQUIRED
ground_alt CDATA #REQUIRED
security_height CDATA #REQUIRED
alt CDATA #REQUIRED
wp_frame CDATA #IMPLIED
qfu CDATA #IMPLIED
home_mode_height CDATA #IMPLIED
geofence_max_alt CDATA #IMPLIED
geofence_max_height CDATA #IMPLIED
geofence_sector CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST sectors>

<!ATTLIST sector
name CDATA #REQUIRED
color CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST corner
name CDATA #REQUIRED>

<!ATTLIST kml
file CDATA #REQUIRED>

<!ATTLIST variables>

<!ATTLIST variable
var CDATA #REQUIRED
type CDATA #IMPLIED
init CDATA #IMPLIED
shortname CDATA #IMPLIED
min CDATA #IMPLIED
max CDATA #IMPLIED
step CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED>

<!ATTLIST abi_binding
name CDATA #REQUIRED
vars CDATA #IMPLIED
id CDATA #IMPLIED
handler CDATA #IMPLIED>

<!ATTLIST modules>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST blocks>

<!ATTLIST block
name CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
on_enter CDATA #IMPLIED
on_exit CDATA #IMPLIED
strip_button CDATA #IMPLIED
strip_icon CDATA #IMPLIED
group CDATA #IMPLIED
key CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST for
var CDATA #REQUIRED
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST heading
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST go
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST path
wpts CDATA #REQUIRED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
until CDATA #IMPLIED
loop CDATA #IMPLIED
break CDATA #IMPLIED>

<!ATTLIST call_once
fun CDATA #REQUIRED
break CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED>

<!ATTLIST xyz
radius CDATA #IMPLIED>

<!ATTLIST home>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
height CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST eight
center CDATA #REQUIRED
turn_around CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
until CDATA #IMPLIED
radius CDATA #REQUIRED>


<!ATTLIST oval
p1 CDATA #REQUIRED
p2 CDATA #REQUIRED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
orientation CDATA #IMPLIED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST guided
commands CDATA #REQUIRED
flags CDATA #IMPLIED
until CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST includes>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST param
name CDATA #REQUIRED
default_value CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST return
reset_stage CDATA #IMPLIED>

=== tudelft/paparazzi/conf/flight_plans/SDB/sdb_bebop_cyberzoo_explorer.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="2.0" ground_alt="0" lat0="51.990634" lon0="4.376789" max_dist_from_home="60" name="Bebop avoid orange TU Delft Cyberzoo" security_height="0.4">
  <header>
    #include "modules/datalink/datalink.h"
    #include "modules/energy/electrical.h"
    #include "modules/radio_control/radio_control.h"
    #include "modules/ahrs/ahrs.h"
    #define NPS_GAZEBO_WORLD "cyberzoo_orange_poles.world"
#include "autopilot.h"
inline void setNav(void){
  autopilot_mode_auto2 = AP_MODE_NAV;
  autopilot_static_set_mode(AP_MODE_NAV);
}
inline void setGuided(void){
  autopilot_mode_auto2 = AP_MODE_GUIDED;
  autopilot_static_set_mode(AP_MODE_GUIDED);
}
</header>
  <waypoints>
    <waypoint lat="51.990631" lon="4.376796" name="HOME"/>
    <waypoint name="CLIMB" x="1.9" y="1.0"/>
    <waypoint name="STDBY" x="1.9" y="1.0"/>
    <waypoint name="TD" x="0.8" y="-1.7"/>
    <waypoint name="GOAL" x="1.9" y="1.0"/>
    <waypoint name="TRAJECTORY" x="1.9" y="1.0"/>
    <waypoint lat="51.9905834" lon="4.3767710" name="_CZ1"/>
    <waypoint lat="51.9906440" lon="4.3767060" name="_CZ2"/>
    <waypoint lat="51.9906860" lon="4.3768080" name="_CZ3"/>
    <waypoint lat="51.9906238" lon="4.3768729" name="_CZ4"/>
    <waypoint lat="51.990595" lon="4.376779" name="_OZ1"/>
    <waypoint lat="51.990640" lon="4.376734" name="_OZ2"/>
    <waypoint lat="51.990667" lon="4.376804" name="_OZ3"/>
    <waypoint lat="51.990623" lon="4.376850" name="_OZ4"/>
  </waypoints>
  <sectors>
    <sector color="red" name="CyberZoo">
      <corner name="_CZ1"/>
      <corner name="_CZ2"/>
      <corner name="_CZ3"/>
      <corner name="_CZ4"/>
    </sector>
    <sector color="#FF9922" name="ObstacleZone">
      <corner name="_OZ1"/>
      <corner name="_OZ2"/>
      <corner name="_OZ3"/>
      <corner name="_OZ4"/>
    </sector>
  </sectors>
  <exceptions>
    <!-- RC lost -->
    <!--exception cond="((radio_control.status == RC_REALLY_LOST) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Standby"/-->
    <!-- Datalink lost (constant RPM descent) -->
    <exception cond="((datalink_time @GT 5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    <!-- Geofencing XY -->
    <exception cond="(!InsideCyberZoo(GetPosX(), GetPosY()) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    <!-- Geofencing Z 2.5 -->
    <exception cond="((GetPosAlt() @GT 3.5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    <!-- Geofencing Z 4.5 (constant RPM descent)-->
    <exception cond="((GetPosAlt() @GT 4.5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- Bat low -->
    <exception cond="(electrical.bat_low @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    <!-- Bat critical (constant RPM no stabilization)-->
    <exception cond="(electrical.bat_critical @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 2)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <!-- <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
      <call_once fun="NavResurrect()"/>
    </block> -->
    <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="autopilot_get_motors_on()" vmode="throttle"/>
    </block>
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() @GT 2.0" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <call_once fun="autopilot_set_in_flight(true)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
      <call_once fun="NavSetWaypointHere(WP_STDBY)"/>
      <stay wp="STDBY"/>
    </block>
    <block key="g" name="START" strip_button="Go" strip_icon="lookfore.png">
      <call_once fun="setGuided()"/>
      <stay wp="STDBY"/>
    </block>
    <block name="STOP">
      <call_once fun="NavSetWaypointHere(WP_STDBY)"/>
      <call_once fun="setNav()"/>
      <stay wp="STDBY"/>
    </block>
    <block key="l" name="land here" strip_button="Land Here" strip_icon="land-right.png">
      <call_once fun="setNav()"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <go wp="TD"/>
      <deroute block="Flare"/>
    </block>
    <block name="Land">
      <call_once fun="setNav()"/>
      <go wp="TD"/>
      <deroute block="Flare"/>
    </block>
    <block name="Flare">
      <exception cond="NavDetectGround()" deroute="Holding point"/>
      <exception cond="!nav_is_in_flight()" deroute="Landed"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Landed"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Landed">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== tudelft/paparazzi/conf/flight_plans/SDB/sdb_bebop_EHVB_Zebra.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">
<flight_plan alt="38" ground_alt="0" lat0="52.1681551" lon0="4.4126468" max_dist_from_home="1070" name="Bebop EHVB Guided" security_height="2">
  <header>
    #include "modules/datalink/datalink.h"
    #include "modules/energy/electrical.h"
    #include "modules/radio_control/radio_control.h"
    #include "modules/ahrs/ahrs.h"
    #include "autopilot.h"
    inline void setNav(void){
      autopilot_mode_auto2 = AP_MODE_NAV;
      autopilot_static_set_mode(AP_MODE_NAV);
    }
    inline void setGuided(void){
      autopilot_mode_auto2 = AP_MODE_GUIDED;
      autopilot_static_set_mode(AP_MODE_GUIDED);
    }
  </header>
  
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="CLIMB" x="10" y="10"/>
    <waypoint name="STDBY" x="66" y="-89"/>
    <waypoint name="TD" x="0" y="0"/>
    <waypoint name="p1" x="100" y="50"/>
    <waypoint name="p2" x="250" y="75"/>
    <waypoint name="p3" x="275" y="-75"/>
    <waypoint name="p4" x="140" y="-120"/>

    <waypoint lat="52.1692076" lon="4.4109107" name="C1"/>
    <waypoint lat="52.1679041" lon="4.4115361" name="C2"/>
    <waypoint lat="52.1667648" lon="4.4121616" name="C3"/>
    <waypoint lat="52.1658477" lon="4.4128391" name="C4"/>
    <waypoint lat="52.1653038" lon="4.4140299" name="C5"/>
    <waypoint lat="52.1649048" lon="4.4164123" name="C6"/>
    <waypoint lat="52.1677828" lon="4.4218386" name="C7"/>
    <waypoint lat="52.1691056" lon="4.4209875" name="C8"/>
    <waypoint lat="52.1709731" lon="4.4187533" name="C9"/>

    <waypoint lat="52.1689778" lon="4.4120424" name="S1"/>
    <waypoint lat="52.1676834" lon="4.4128426" name="S2"/>
    <waypoint lat="52.1670734" lon="4.4131911" name="S3"/>
    <waypoint lat="52.1661943" lon="4.4137259" name="S4"/>
    <waypoint lat="52.1658967" lon="4.4147855" name="S5"/>
    <waypoint lat="52.1655207" lon="4.4159736" name="S6"/>
    <waypoint lat="52.1678818" lon="4.4205845" name="S7"/>
    <waypoint lat="52.1686448" lon="4.4200855" name="S8"/>
    <waypoint lat="52.1703410" lon="4.4180236" name="S9"/>
  </waypoints>

  <sectors>
    <sector color="red" name="Flyzone">
      <corner name="C1"/>
      <corner name="C2"/>
      <corner name="C3"/>
      <corner name="C4"/>
      <corner name="C5"/>
      <corner name="C6"/>
      <corner name="C7"/>
      <corner name="C8"/>
      <corner name="C9"/>
    </sector>
    <sector color="orange" name="SoftGeofence">
      <corner name="S1"/>
      <corner name="S2"/>
      <corner name="S3"/>
      <corner name="S4"/>
      <corner name="S5"/>
      <corner name="S6"/>
      <corner name="S7"/>
      <corner name="S8"/>
      <corner name="S9"/>
    </sector>
  </sectors>
<!-- 
  <exceptions>
    <exception cond="((datalink_time @GT 5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    
    <exception cond="(!InsideFlyzone(GetPosX(), GetPosY()) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>

    <exception cond="((GetPosAlt() @GT 100.0) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>

    <exception cond="(electrical.bat_low @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
      
    <exception cond="(electrical.bat_critical @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
  </exceptions> -->

  <exceptions>
    <exception cond="(!InsideFlyzone(GetPosX(), GetPosY()) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>

    <exception cond="(!InsideSoftGeofence(GetPosX(), GetPosY()) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Return Safe"/>

    <exception cond="((datalink_time @GT 5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>

    <exception cond="((GetPosAlt() @GT 150.0) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>

    <exception cond="(electrical.bat_low @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
      
    <exception cond="(electrical.bat_critical @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
  </exceptions>

  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    
    <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() @GT 2.0" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <call_once fun="autopilot_set_in_flight(true)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
      <call_once fun="NavSetWaypointHere(WP_STDBY)"/>
      <stay wp="STDBY"/>
    </block>

    <block key="g" name="START" strip_button="Go Guided" strip_icon="lookfore.png">
      <call_once fun="setGuided()"/>
      <stay wp="STDBY"/>
    </block>
    
    <block name="STOP">
      <call_once fun="NavSetWaypointHere(WP_STDBY)"/>
      <call_once fun="setNav()"/>
      <stay wp="STDBY"/>
    </block>

    <block name="Route Path" strip_button="Route Path" strip_icon="path.png">
      <call_once fun="setNav()"/>
      <go wp="p1"/>
      
      <go from="p1" hmode="route" wp="p2"/>
      <go from="p2" hmode="route" wp="p3"/>
      <go from="p3" hmode="route" wp="p4"/>
      <go from="p4" hmode="route" wp="p1"/>
      
      <deroute block="Route Path"/>
    </block>

    <block name="Return Safe" strip_button="Return Safe" strip_icon="home.png">
      <call_once fun="setNav()"/>
      <stay wp="HOME"/>
    </block>
    
    <block key="l" name="land here" strip_button="Land Here" strip_icon="land-right.png">
      <call_once fun="setNav()"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <deroute block="Flare"/>
    </block>
    
    <block name="Land">
      <call_once fun="setNav()"/>
      <deroute block="Flare"/>
    </block>
    
    <block name="Flare">
      <!-- <exception cond="NavDetectGround()" deroute="Holding point"/> -->
      <exception cond="!nav_is_in_flight()" deroute="Landed"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Landed"/>
      <!-- <call_once fun="NavStartDetectGround()"/> -->
      <stay climb="-0.8" vmode="climb" wp="TD"/>
    </block>
    
    <block name="Landed">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== tudelft/paparazzi/conf/flight_plans/tudelft/oneloop_cyberzoo.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="1.0" ground_alt="0" lat0="51.990634" lon0="4.376789" max_dist_from_home="60" name="Safe TU Delft Cyberzoo" security_height="0.4">
  <header>
    #include "autopilot.h"
    #include "modules/datalink/datalink.h"
    #include "modules/energy/electrical.h"
    #include "modules/radio_control/radio_control.h"
    #include "modules/ahrs/ahrs.h"
    #include "modules/gps/gps.h"
    #include "modules/rotwing_drone/rotwing_state.h"
    <!-- #include "sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.h" -->
    inline static void set_demo_skew(void) {
      float amplitude_skew_demo       = (rotwing_demo_max_skew - rotwing_demo_min_skew) / 2;
      float offset_skew_demo          = (rotwing_demo_max_skew + rotwing_demo_min_skew) / 2;
      float time_skew_demo            = (float) rotwing_demo_timestep / NAVIGATION_FREQUENCY;
      float angle_skew_demo           = amplitude_skew_demo * (-cosf(2 * M_PI * rotwing_demo_freq_skew * time_skew_demo)) + offset_skew_demo;
      rotwing_state.sp_skew_angle_deg = angle_skew_demo;
      rotwing_demo_timestep++;
    }
</header>
  <waypoints>
    <waypoint lat="51.990631" lon="4.376796" name="HOME"/>
    <waypoint name="CLIMB" x="1.9" y="1.0"/>
    <waypoint name="STDBY" x="0.5" y="0.3"/>
    <waypoint name="p5" x="0.2" y="0.3"/>
    <waypoint name="TD" x="0.8" y="-1.7"/>
    <waypoint name="FOLLOW" x="-1" y="5"/>
    <waypoint lat="51.9905979" lon="4.3767279" name="CZ1"/>
    <waypoint lat="51.9906685" lon="4.3767327" name="CZ2"/>
    <waypoint lat="51.9906652" lon="4.3768481" name="CZ3"/>
    <waypoint lat="51.9905941" lon="4.3768441" name="CZ4"/>
    <waypoint lat="51.9906028" lon="4.3767375" name="p1"/>
    <waypoint lat="51.9906633" lon="4.3767411" name="p2"/>
    <waypoint lat="51.9906601" lon="4.3768415" name="p3"/>
    <waypoint lat="51.9905979" lon="4.3768386" name="p4"/>
  </waypoints>
  <sectors>
    <sector color="blue" name="CyberZoo">
      <corner name="CZ1"/>
      <corner name="CZ2"/>
      <corner name="CZ3"/>
      <corner name="CZ4"/>
    </sector>
    <sector color="red" name="Flyzone">
      <corner name="p1"/>
      <corner name="p2"/>
      <corner name="p3"/>
      <corner name="p4"/>
    </sector>
  </sectors>
  <variables>
    <variable var="rotwing_demo_max_skew"  init="50.0f" type="float"  min="0"    step="1"    max="80" shortname="demo_max_skew"/>
    <variable var="rotwing_demo_min_skew"  init="0.0f"  type="float"  min="0"    step="1"    max="80" shortname="demo_min_skew"/>
    <variable var="rotwing_demo_freq_skew" init="0.1f"  type="float"  min="0.01" step="0.05" max="10" shortname="demo_freq_skew"/>
    <variable var="rotwing_demo_timestep"  init="0"     type="uint32_t"/>
  </variables>
  <exceptions>
    <!--Soft Geofencing (go back to Standby)-->
    <exception cond="Or(!InsideFlyzone(GetPosX(), GetPosY()), GetPosAlt() @GT 20.0) @AND
     !(nav_block == IndexOfBlock('Wait GPS')) @AND
     !(nav_block == IndexOfBlock('Geo init'))" deroute="safe"/>
    <!-- Hard Geofencing (Kill) -->
    <exception cond="(Or(!InsideCyberZoo(GetPosX(), GetPosY()), GetPosAlt() @GT 80.0) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- RC lost -->
    <exception cond="((radio_control.status == RC_REALLY_LOST) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- Datalink lost  -->
    <exception cond="((datalink_time @GT 5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- Bat low (constant RPM descent)-->
    <exception cond="(electrical.bat_low @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    <!-- Bat critical (constant RPM no stabilization)-->
    <exception cond="(electrical.bat_critical @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 2)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
      <call_once fun="NavResurrect()"/>
    </block>
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() @GT 0.8" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
      <stay wp="STDBY"/>
    </block>
    <block key="d" name="Standby Demo" on_enter="rotwing_state.force_skew=true" on_exit="rotwing_state.force_skew=false; rotwing_demo_timestep = 0">  
      <stay wp="STDBY" pre_call="set_demo_skew()"/>
    </block>
    <block name="go_p5">
      <stay wp="p5"/>
    </block>
    <block name="safe">
      <stay wp="p5"/>
      <exception cond="NavBlockTime() @GT 5" deroute="go_p5"/>
    </block>
    <block name="FOLLOW">
        <call_once fun="rotwing_state_set(ROTWING_STATE_REQUEST_HOVER)"/>
        <stay wp="FOLLOW"/>
    </block>
    <block key="l" name="land here" strip_button="land here" strip_icon="land-right.png">
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <go wp="TD"/>
      <deroute block="Flare"/>
    </block>
    <block name="Land">
      <go wp="TD"/>
      <deroute block="Flare"/>
    </block>
    <block name="Flare">
      <exception cond="NavDetectGround()" deroute="Holding point"/>
      <exception cond="!nav_is_in_flight()" deroute="Landed"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Landed"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Safe landing">
      <exception cond="!nav_is_in_flight()" deroute="Manual"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Manual"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Manual">
      <set value="AP_MODE_ATTITUDE_DIRECT" var="autopilot_mode_auto2"/>
      <stay wp="STDBY"/>
    </block>
    <block name="Landed">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>
