=== tudelft/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (header?,waypoints,sectors?,variables?,modules?,includes?,exceptions?,blocks)>

<!ELEMENT procedure (param*,header?,waypoints?,sectors?,exceptions?,blocks?)>

<!ELEMENT header (#PCDATA)>

<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT sectors (sector|kml)*>
<!ELEMENT sector (corner,corner,corner+)>
<!ELEMENT corner EMPTY>
<!ELEMENT kml EMPTY>

<!ELEMENT variables (variable|abi_binding)*>
<!ELEMENT variable EMPTY>
<!ELEMENT abi_binding EMPTY>

<!ELEMENT modules (module*)>
<!ELEMENT module  (configure|define)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>

<!ELEMENT includes (include*)>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|home|path|guided)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path|guided)*>
<!ELEMENT for (exception|while|heading|attitude|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path|guided)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_once EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT home EMPTY>
<!ELEMENT eight EMPTY>
<!ELEMENT oval EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT path EMPTY>
<!ELEMENT guided EMPTY>


<!ATTLIST flight_plan
name CDATA #REQUIRED
lat0 CDATA #REQUIRED
lon0 CDATA #REQUIRED
max_dist_from_home CDATA #REQUIRED
ground_alt CDATA #REQUIRED
security_height CDATA #REQUIRED
alt CDATA #REQUIRED
wp_frame CDATA #IMPLIED
qfu CDATA #IMPLIED
home_mode_height CDATA #IMPLIED
geofence_max_alt CDATA #IMPLIED
geofence_max_height CDATA #IMPLIED
geofence_sector CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST sectors>

<!ATTLIST sector
name CDATA #REQUIRED
color CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST corner
name CDATA #REQUIRED>

<!ATTLIST kml
file CDATA #REQUIRED>

<!ATTLIST variables>

<!ATTLIST variable
var CDATA #REQUIRED
type CDATA #IMPLIED
init CDATA #IMPLIED
shortname CDATA #IMPLIED
min CDATA #IMPLIED
max CDATA #IMPLIED
step CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED>

<!ATTLIST abi_binding
name CDATA #REQUIRED
vars CDATA #IMPLIED
id CDATA #IMPLIED
handler CDATA #IMPLIED>

<!ATTLIST modules>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST blocks>

<!ATTLIST block
name CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
on_enter CDATA #IMPLIED
on_exit CDATA #IMPLIED
strip_button CDATA #IMPLIED
strip_icon CDATA #IMPLIED
group CDATA #IMPLIED
key CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST for
var CDATA #REQUIRED
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST heading
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST go
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST path
wpts CDATA #REQUIRED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
until CDATA #IMPLIED
loop CDATA #IMPLIED
break CDATA #IMPLIED>

<!ATTLIST call_once
fun CDATA #REQUIRED
break CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED>

<!ATTLIST xyz
radius CDATA #IMPLIED>

<!ATTLIST home>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
height CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST eight
center CDATA #REQUIRED
turn_around CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
until CDATA #IMPLIED
radius CDATA #REQUIRED>


<!ATTLIST oval
p1 CDATA #REQUIRED
p2 CDATA #REQUIRED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
orientation CDATA #IMPLIED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST guided
commands CDATA #REQUIRED
flags CDATA #IMPLIED
until CDATA #IMPLIED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
nav_type CDATA #IMPLIED
nav_params CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST includes>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST param
name CDATA #REQUIRED
default_value CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST return
reset_stage CDATA #IMPLIED>

=== tudelft/paparazzi/conf/flight_plans/AM/Ship_box_EHVB.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="55" ground_alt="0" lat0="52.168595" lon0="4.412444" max_dist_from_home="700" name="Overactuated vehicle Valkenburg" security_height="20">
  <header>
    #include "autopilot.h"
    #include "modules/datalink/datalink.h"
    #include "modules/Overactuated_vehicle/Overactuated_mixing.h"
    static inline bool delay_test_rc(bool test, int delay) {
      static int nb = 0;
        if (test) {
        nb++;
        if (nb == delay) {
          nb = 0;
          return true;
        }
        return false;
      } else {
        nb = 0;
        return false;
      }
    }
</header>
  <waypoints>
    <waypoint name="HOME" x="12.6" y="-48.7"/>
    <waypoint name="CLIMB" x="62.6" y="-80.4"/>
    <waypoint lat="52.1682794" lon="4.4139911" name="STDBY"/>
    <waypoint lat="52.1694940" lon="4.4155585" name="p1"/>
    <waypoint lat="52.167791" lon="4.416685" name="p2"/>
    <waypoint lat="52.1671481" lon="4.4141374" name="p3"/>
    <waypoint lat="52.1689418" lon="4.4132070" name="p4"/>
    <waypoint lat="52.1681602" lon="4.4127708" name="TD"/>
    <waypoint lat="52.1680902" lon="4.4148029" name="APP"/>
    <waypoint lat="52.1686922" lon="4.4149181" name="FOLLOW"/>
    <waypoint lat="52.169599" lon="4.417198" name="FOLLOW_ARUCO"/>
    <waypoint lat="52.169742" lon="4.411045" name="C1"/>
    <waypoint lat="52.168740" lon="4.407411" name="C2"/>
    <waypoint lat="52.166515" lon="4.408235" name="C3"/>
    <waypoint lat="52.164107" lon="4.410072" name="C4"/>
    <waypoint lat="52.162922" lon="4.412524" name="C5"/>
    <waypoint lat="52.163563" lon="4.417368" name="C6"/>
    <waypoint lat="52.166336" lon="4.424451" name="C7"/>
    <waypoint lat="52.169063" lon="4.423567" name="C8"/>
    <waypoint lat="52.172299" lon="4.421081" name="C9"/>
    <waypoint lat="52.170384" lon="4.416553" name="FLY1"/>
    <waypoint lat="52.169892" lon="4.414011" name="FLY2"/>
    <waypoint lat="52.169201" lon="4.411394" name="FLY3"/>
    <waypoint lat="52.166201" lon="4.413254" name="FLY4"/>
    <waypoint lat="52.165909" lon="4.415910" name="FLY5"/>
    <waypoint lat="52.166849" lon="4.419219" name="FLY6"/>
    <waypoint lat="52.167911" lon="4.418455" name="FLY7"/>
    <waypoint lat="52.168774" lon="4.417835" name="FLY8"/>
    <waypoint lat="52.169599" lon="4.417198" name="FLY9"/>
  </waypoints>
  <sectors>
    <sector color="orange" name="Safe_area">
      <corner name="FLY1"/>
      <corner name="FLY2"/>
      <corner name="FLY3"/>
      <corner name="FLY4"/>
      <corner name="FLY5"/>
      <corner name="FLY6"/>
      <corner name="FLY7"/>
      <corner name="FLY8"/>
      <corner name="FLY9"/>
    </sector>
    <sector color="red" name="Flight_area">
      <corner name="C1"/>
      <corner name="C2"/>
      <corner name="C3"/>
      <corner name="C4"/>
      <corner name="C5"/>
      <corner name="C6"/>
      <corner name="C7"/>
      <corner name="C8"/>
      <corner name="C9"/>
    </sector>
  </sectors>
  <exceptions>

  </exceptions>
  <blocks>
    <block name="Enter_AP_MODE_RC_DIRECT">
      <set value="AP_MODE_RC_DIRECT" var="autopilot.mode"/>
    </block>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid() || !state.ned_initialized_i"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" pre_call="NavKillThrottle()" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== tudelft/paparazzi/conf/flight_plans/tudelft/MER_motor_pn_flightplan.xml
<?xml version="1.0"?>
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">
<flight_plan alt="1.0" ground_alt="0" lat0="51.990634" lon0="4.376789" max_dist_from_home="10" name="Bebop avoid orange TU Delft Cyberzoo" security_height="0.4">
  <header>
    #include "modules/datalink/datalink.h"
    #include "modules/energy/electrical.h"
    #include "modules/radio_control/radio_control.h"
    #include "modules/ahrs/ahrs.h"
    #include "modules/motor_pn/motor_pn.h"
    #include "modules/loggers/logger_file.h"
    #define NPS_GAZEBO_WORLD "cyberzoo.world"
#include "autopilot.h"
inline void setNav(void){
  autopilot_mode_auto2 = AP_MODE_NAV;
  autopilot_static_set_mode(AP_MODE_NAV);
}
inline void setGuided(void){
  autopilot_mode_auto2 = AP_MODE_GUIDED;
  autopilot_static_set_mode(AP_MODE_GUIDED);
}
</header>
  <waypoints>
    <waypoint lat="51.990631" lon="4.376796" name="HOME"/>
    <waypoint name="CLIMB" x="1.9" y="1.0"/>
    <waypoint name="STDBY" x="1.9" y="1.0"/>
    <waypoint name="TD" x="0.8" y="-1.7" height="0.5"/>
    <waypoint name="GOAL" x="1.9" y="1.0"/>
    <waypoint name="TRAJECTORY" x="1.9" y="1.0"/>
    <waypoint name="RETREAT" x="1.9" y="1.0"/>
    <waypoint lat="51.9905834" lon="4.3767710" name="_CZ1"/>
    <waypoint lat="51.9906440" lon="4.3767060" name="_CZ2"/>
    <waypoint lat="51.9906860" lon="4.3768080" name="_CZ3"/>
    <waypoint lat="51.9906238" lon="4.3768729" name="_CZ4"/>
    <waypoint lat="51.9906006" lon="4.3767764" name="_OZ1"/>
    <waypoint lat="51.9906405" lon="4.3767316" name="_OZ2"/>
    <waypoint lat="51.9906687" lon="4.3768025" name="_OZ3"/>
    <waypoint lat="51.9906273" lon="4.3768438" name="_OZ4"/>
  </waypoints>
  <sectors>
    <sector color="red" name="CyberZoo">
      <corner name="_CZ1"/>
      <corner name="_CZ2"/>
      <corner name="_CZ3"/>
      <corner name="_CZ4"/>
    </sector>
    <sector color="#FF9922" name="ObstacleZone">
      <corner name="_OZ1"/>
      <corner name="_OZ2"/>
      <corner name="_OZ3"/>
      <corner name="_OZ4"/>
    </sector>
  </sectors>
  <modules>
   	<module name="motor_pn"/>
  </modules>
  <exceptions>
    <!-- GPS Lost (KILL Motors) -->
    <exception cond="((GpsIsLost() == true) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Emergency Landing')) @AND
      (autopilot_in_flight() == true) )" deroute="KILL"/>
    <!-- Datalink Lost -->
    <exception cond="((datalink_time @GT 2) @AND 
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Emergency Landing')) @AND
      (autopilot_in_flight() == true) )" deroute="Emergency Landing"/>
    <!-- Geofencing XY -->
    <exception cond="(!InsideCyberZoo(GetPosX(), GetPosY()) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Emergency Landing')) @AND
      (autopilot_in_flight() == true) )" deroute="Emergency Landing"/>
    <!-- Geofencing Z 3.5 -->
    <exception cond="((GetPosAlt() @GT 3.5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Emergency Landing')) @AND
      (autopilot_in_flight() == true) )" deroute="Emergency Landing"/>
    <!-- Geofencing Z 4.5 -->
    <exception cond="((GetPosAlt() @GT 4.5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      (autopilot_in_flight() == true) )" deroute="Emergency Landing"/>
    <!-- Bat Low -->
    <exception cond="(electrical.bat_low @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Emergency Landing')) @AND
      (autopilot_in_flight() == true) )" deroute="Emergency Landing"/>
    <!-- Bat Critical -->
    <exception cond="(electrical.bat_critical @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Emergency Landing')) @AND
      (autopilot_in_flight() == true) )" deroute="Emergency Landing"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 2)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
      <call_once fun="NavResurrect()"/>
    </block>
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <call_once fun="NavSetWaypointHere(WP_TD)"/> 
      <exception cond="GetPosAlt() @GT 0.8" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
      <call_once fun="NavSetWaypointHere(WP_STDBY)"/>
      <stay wp="STDBY"/>
    </block>
    <block key="g" name="START" strip_button="Go" strip_icon="lookfore.png">
      <call_once fun="setGuided()"/>
      <call_once fun="logger_file_start()"/>
      <call_once fun="pn_start()"/>
      <stay wp="STDBY"/>
    </block>
    <block name="STOP">
      <call_once fun="logger_file_stop()"/>
      <call_once fun="pn_stop()"/>
      <call_once fun="setNav()"/>
      <stay wp="STDBY"/>
    </block>
    <block name="RETREAT">
      <exception cond="block_time @GT 2.0" deroute="STOP"/>
      <call_once fun="NavSetWaypointHere(WP_RETREAT)"/>
      <stay wp="RETREAT"/>
    </block>
    <block key="e" name="Emergency Landing">
      <call_once fun="pn_stop()"/>
      <call_once fun="setNav()"/>
      <exception cond="!nav_is_in_flight()" deroute="KILL"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="KILL"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="-1.25" vmode="climb" wp="TD"/>
    </block>
    <block key="i" name="Immediate Landing" strip_button="Immediate Landing" strip_icon="land-right.png">
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <deroute block="Land"/>
    </block>
    <block key="l" name="Land">
      <exception cond="0.55 @GEQ GetPosAlt()" deroute="Flare"/>
      <exception cond="block_time @GT 5" deroute="Flare"/>
      <go wp="TD"/> 
      <deroute block="Flare"/>
    </block>
    <block name="Flare">
      <exception cond="!nav_is_in_flight()" deroute="Landed"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Landed"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Landed">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="KILL">
      <call_once fun="autopilot_set_mode(AP_MODE_KILL)"/>
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== tudelft/paparazzi/conf/flight_plans/AM/overactuated_vehicle_cyberzoo_optitrack.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="1.0" ground_alt="0" lat0="51.990634" lon0="4.376789" max_dist_from_home="60" name="overactuated_vehicle_cyberzoo_optitrack" security_height="0.4">
  <header>
    #include "modules/datalink/datalink.h"
    #include "modules/energy/electrical.h"
    #include "modules/radio_control/radio_control.h"
</header>
  <waypoints>
    <waypoint lat="51.990631" lon="4.376796" name="HOME"/>
    <waypoint name="CLIMB" x="1.9" y="1.0"/>
    <waypoint name="STDBY" x="0.5" y="0.3"/>
    <waypoint name="p5" x="0.2" y="0.3"/>
    <waypoint name="TD" x="0.8" y="-1.7"/>
    <waypoint name="SIXDOF" x="2" y="-1"/>
    <waypoint name="ARUCO" x="3" y="1"/>
    <waypoint lat="51.9905979" lon="4.3767279" name="CZ1"/>
    <waypoint lat="51.9906685" lon="4.3767327" name="CZ2"/>
    <waypoint lat="51.9906652" lon="4.3768481" name="CZ3"/>
    <waypoint lat="51.9905941" lon="4.3768441" name="CZ4"/>
    <waypoint lat="51.9906028" lon="4.3767375" name="p1"/>
    <waypoint lat="51.9906633" lon="4.3767411" name="p2"/>
    <waypoint lat="51.9906601" lon="4.3768415" name="p3"/>
    <waypoint lat="51.9905979" lon="4.3768386" name="p4"/>
  </waypoints>
  <sectors>
    <sector color="blue" name="CyberZoo">
      <corner name="CZ1"/>
      <corner name="CZ2"/>
      <corner name="CZ3"/>
      <corner name="CZ4"/>
    </sector>
    <sector color="red" name="Flyzone">
      <corner name="p1"/>
      <corner name="p2"/>
      <corner name="p3"/>
      <corner name="p4"/>
    </sector>
  </sectors>
  <exceptions>
    <!--Soft Geofencing (go back to Standby)-->
    <exception cond="Or(!InsideFlyzone(GetPosX(), GetPosY()), GetPosAlt() @GT 20.0) @AND
     !(nav_block == IndexOfBlock('Wait GPS')) @AND
     !(nav_block == IndexOfBlock('Geo init'))" deroute="safe"/>
    <!-- Hard Geofencing (Kill) -->
    <exception cond="(Or(!InsideCyberZoo(GetPosX(), GetPosY()), GetPosAlt() @GT 80.0) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="landed"/>
    <!-- RC lost -->
    <exception cond="((radio_control.status == RC_REALLY_LOST) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="landed"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 2)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" pre_call="NavKillThrottle()" vmode="throttle"/>
    </block>
    <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
      <call_once fun="NavResurrect()"/>
    </block>
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() @GT 0.8" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block name="Pre-Standby">
      <call_once fun="NavSetWaypointHere(WP_STDBY)"/>
    </block>
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <stay wp="STDBY"/>
    </block>
    <block name="Standby_APP">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <stay wp="STDBY"/>
    </block>
    <block name="Sixdof">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="SIXDOF"/>
    </block>  
    <block name="Sixdof_APP">
      <set value="1" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="SIXDOF"/>
    </block>  
    <block name="Aruco">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="ARUCO"/>
    </block>  
    <block name="Aruco_APP">
      <set value="1" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="ARUCO"/>
    </block>  
    <block name="go_p5">
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <stay wp="p5"/>
    </block>
    <block name="safe">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <stay wp="p5"/>
      <exception cond="NavBlockTime() @GT 5" deroute="go_p5"/>
    </block>
    <block key="l" name="land here" strip_button="land here" strip_icon="land-right.png">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <go wp="TD"/>
      <deroute block="flare"/>
    </block>
    <block name="Land">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <go wp="TD"/>
      <deroute block="flare"/>
    </block>
    <block name="descend">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <exception cond="!(stateGetPositionEnu_f()->z > 12.0)" deroute="flare"/>
      <stay climb="-1.5" vmode="climb" wp="TD"/>
    </block>
    <block name="flare">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <stay climb="-0.2" vmode="climb" wp="TD"/>
      <exception cond="!(stateGetPositionEnu_f()->z > 1.0)" deroute="flare_low"/>
      <exception cond="agl_dist_valid @AND !(agl_dist_value > 0.50)" deroute="flare_low"/>
    </block>
    <block name="flare_low">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <!-- <exception cond="NavDetectGround()" deroute="Holding point"/> -->
      <exception cond="detect_ground_on_landing()" deroute="landed"/>
      <!-- <call_once fun="NavStartDetectGround()"/> -->
      <stay climb="-0.5" vmode="climb" wp="TD"/>
    </block>
    <block name="landed">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>
